package com.tig.ecomerce.seeders;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import com.tig.ecomerce.model.Category;
import com.tig.ecomerce.model.City;
import com.tig.ecomerce.model.Department;
import com.tig.ecomerce.model.PaymentMethod;
import com.tig.ecomerce.model.State;
import com.tig.ecomerce.model.StateType;
import com.tig.ecomerce.model.StreetType;
import com.tig.ecomerce.service.CategoryService;
import com.tig.ecomerce.service.CityService;
import com.tig.ecomerce.service.DepartmentService;
import com.tig.ecomerce.service.PaymentMethodService;
import com.tig.ecomerce.service.StateService;
import com.tig.ecomerce.service.StateTypeService;
import com.tig.ecomerce.service.StreetTypeService;

@Component
public class DatabseSeeder implements CommandLineRunner {
	
	@Autowired
	private CityService cityService;
	@Autowired
	private DepartmentService deparmentService;
	@Autowired
	private StreetTypeService streetTypeService;
	@Autowired
	private StateTypeService stateTypeService;
	@Autowired
	private StateService stateService;
	@Autowired
	private CategoryService categoryService;
	@Autowired
	private PaymentMethodService paymentmethodService;
	
	@Override
	public void run(String... args) throws Exception {
		setUpDepartments();
		setUpCities();
		setUpStreetTypes();
		setUpStateTypes();
		setUpStates();
		setUpCategories();
		setUpPaymentMethods();
	}
	
	private void setUpPaymentMethods() {
		if(paymentmethodService.getPaymentMethods().isEmpty()) {
			List<PaymentMethod> paymentMehods = new ArrayList<>();
			paymentMehods.add(new PaymentMethod(1, "Trjeta de crédito"));
			paymentMehods.add(new PaymentMethod(2, "Tarjeta de débito"));
			paymentMehods.add(new PaymentMethod(3, "Transferencia desde tu banco con PSE"));
			paymentMehods.add(new PaymentMethod(4, "Pago en efectivo con Efecty"));
			paymentmethodService.saveAllPaymentMethods(paymentMehods);
 		}
	}
	
	private void setUpCategories() {
		if(categoryService.getCategories().isEmpty()) {
			List<Category> categories = new ArrayList<>();
			categories.add(new Category("Decoración para el hogar"));
			categories.add(new Category("Joyería artesanal"));
			categories.add(new Category("Artículos de papelería"));
			categories.add(new Category("Ropa y accesorios"));
			categories.add(new Category("Juguetes y juegos"));
			categories.add(new Category("Artesanías de arte"));
			categories.add(new Category("Artículos de cuero"));
			categories.add(new Category("Esculturas de metal"));
			categories.add(new Category("Vidrio soplado"));
			categories.add(new Category("Artesanías de madera"));
			categories.add(new Category("Artículos de jardín"));
			categories.add(new Category("Artesanías de papel maché"));
			categories.add(new Category("Artículos de metalurgia"));
			
			categoryService.saveAllCategories(categories);
		}
	}
	
	private void setUpStates() {
		if(stateService.getStates().isEmpty()) {
			List<State> states = new ArrayList<>();
			
			states.add(new State(1,"Activo", stateTypeService.getStateTypeById(1)));
			states.add(new State(2,"Inactivo", stateTypeService.getStateTypeById(1)));
			states.add(new State(3,"Abierto", stateTypeService.getStateTypeById(2)));
			states.add(new State(4,"Cerrado", stateTypeService.getStateTypeById(2)));
			states.add(new State(5,"Por pagar", stateTypeService.getStateTypeById(3)));
			states.add(new State(6,"Pagada", stateTypeService.getStateTypeById(3)));
			states.add(new State(7,"Cancelada", stateTypeService.getStateTypeById(3)));
			
			stateService.saveAllStates(states);
		}

	}
	
	private void setUpStateTypes() {
		if(stateTypeService.getStatetypes().isEmpty()) {
			List<StateType> stateTypes = new ArrayList<>();
			stateTypes.add(new StateType(1, "state"));
			stateTypes.add(new StateType(2, "shoppingCartsState"));
			stateTypes.add(new StateType(3, "invoice"));
			
			stateTypeService.saveAllStatetypes(stateTypes);
		}

	}
	
	
	private void setUpStreetTypes() {
		
		if(streetTypeService.getStreetTypes().isEmpty()) {
			List<StreetType> streetTypes = new ArrayList<>();
			
			streetTypes.add(new StreetType(1, "Avenida"));
			streetTypes.add(new StreetType(2, "Avenida Calle"));
			streetTypes.add(new StreetType(3, "Avenida Carrera"));
			streetTypes.add(new StreetType(4, "Calle"));
			streetTypes.add(new StreetType(5, "Carrera"));
			streetTypes.add(new StreetType(6, "Circular"));
			streetTypes.add(new StreetType(7, "Circunvalar"));
			streetTypes.add(new StreetType(8, "Diagonal"));
			streetTypes.add(new StreetType(9, "Manzana"));
			streetTypes.add(new StreetType(10, "Transversal"));
			streetTypes.add(new StreetType(11, "Vía"));

			
			streetTypeService.saveAllStreetTypes(streetTypes);
		}
		
	}
	
	
	private void setUpCities() {
		if(cityService.getCities().isEmpty()) {
			List<City> cities = new ArrayList<>();
			
			cities.add(new City(1,"Abriaquí", deparmentService.getDepartmentById(5)));
			cities.add(new City(2,"Acacías", deparmentService.getDepartmentById(50)));
			cities.add(new City(3,"Acandí", deparmentService.getDepartmentById(27)));
			cities.add(new City(4,"Acevedo", deparmentService.getDepartmentById(41)));
			cities.add(new City(5,"Achí", deparmentService.getDepartmentById(13)));
			cities.add(new City(6,"Agrado", deparmentService.getDepartmentById(41)));
			cities.add(new City(7,"Agua de Dios", deparmentService.getDepartmentById(25)));
			cities.add(new City(8,"Aguachica", deparmentService.getDepartmentById(20)));
			cities.add(new City(9,"Aguada", deparmentService.getDepartmentById(68)));
			cities.add(new City(10,"Aguadas", deparmentService.getDepartmentById(17)));
			cities.add(new City(11,"Aguazul", deparmentService.getDepartmentById(85)));
			cities.add(new City(12,"Agustín Codazzi", deparmentService.getDepartmentById(20)));
			cities.add(new City(13,"Aipe", deparmentService.getDepartmentById(41)));
			cities.add(new City(14,"Albania", deparmentService.getDepartmentById(18)));
			cities.add(new City(15,"Albania", deparmentService.getDepartmentById(44)));
			cities.add(new City(16,"Albania", deparmentService.getDepartmentById(68)));
			cities.add(new City(17,"Albán", deparmentService.getDepartmentById(25)));
			cities.add(new City(18,"Albán (San José)", deparmentService.getDepartmentById(52)));
			cities.add(new City(19,"Alcalá", deparmentService.getDepartmentById(76)));
			cities.add(new City(20,"Alejandria", deparmentService.getDepartmentById(5)));
			cities.add(new City(21,"Algarrobo", deparmentService.getDepartmentById(47)));
			cities.add(new City(22,"Algeciras", deparmentService.getDepartmentById(41)));
			cities.add(new City(23,"Almaguer", deparmentService.getDepartmentById(19)));
			cities.add(new City(24,"Almeida", deparmentService.getDepartmentById(15)));
			cities.add(new City(25,"Alpujarra", deparmentService.getDepartmentById(73)));
			cities.add(new City(26,"Altamira", deparmentService.getDepartmentById(41)));
			cities.add(new City(27,"Alto Baudó (Pie de Pato)", deparmentService.getDepartmentById(27)));
			cities.add(new City(28,"Altos del Rosario", deparmentService.getDepartmentById(13)));
			cities.add(new City(29,"Alvarado", deparmentService.getDepartmentById(73)));
			cities.add(new City(30,"Amagá", deparmentService.getDepartmentById(5)));
			cities.add(new City(31,"Amalfi", deparmentService.getDepartmentById(5)));
			cities.add(new City(32,"Ambalema", deparmentService.getDepartmentById(73)));
			cities.add(new City(33,"Anapoima", deparmentService.getDepartmentById(25)));
			cities.add(new City(34,"Ancuya", deparmentService.getDepartmentById(52)));
			cities.add(new City(35,"Andalucía", deparmentService.getDepartmentById(76)));
			cities.add(new City(36,"Andes", deparmentService.getDepartmentById(5)));
			cities.add(new City(37,"Angelópolis", deparmentService.getDepartmentById(5)));
			cities.add(new City(38,"Angostura", deparmentService.getDepartmentById(5)));
			cities.add(new City(39,"Anolaima", deparmentService.getDepartmentById(25)));
			cities.add(new City(40,"Anorí", deparmentService.getDepartmentById(5)));
			cities.add(new City(41,"Anserma", deparmentService.getDepartmentById(17)));
			cities.add(new City(42,"Ansermanuevo", deparmentService.getDepartmentById(76)));
			cities.add(new City(43,"Anzoátegui", deparmentService.getDepartmentById(73)));
			cities.add(new City(44,"Anzá", deparmentService.getDepartmentById(5)));
			cities.add(new City(45,"Apartadó", deparmentService.getDepartmentById(5)));
			cities.add(new City(46,"Apulo", deparmentService.getDepartmentById(25)));
			cities.add(new City(47,"Apía", deparmentService.getDepartmentById(66)));
			cities.add(new City(48,"Aquitania", deparmentService.getDepartmentById(15)));
			cities.add(new City(49,"Aracataca", deparmentService.getDepartmentById(47)));
			cities.add(new City(50,"Aranzazu", deparmentService.getDepartmentById(17)));
			cities.add(new City(51,"Aratoca", deparmentService.getDepartmentById(68)));
			cities.add(new City(52,"Arauca", deparmentService.getDepartmentById(81)));
			cities.add(new City(53,"Arauquita", deparmentService.getDepartmentById(81)));
			cities.add(new City(54,"Arbeláez", deparmentService.getDepartmentById(25)));
			cities.add(new City(55,"Arboleda (Berruecos)", deparmentService.getDepartmentById(52)));
			cities.add(new City(56,"Arboledas", deparmentService.getDepartmentById(54)));
			cities.add(new City(57,"Arboletes", deparmentService.getDepartmentById(5)));
			cities.add(new City(58,"Arcabuco", deparmentService.getDepartmentById(15)));
			cities.add(new City(59,"Arenal", deparmentService.getDepartmentById(13)));
			cities.add(new City(60,"Argelia", deparmentService.getDepartmentById(5)));
			cities.add(new City(61,"Argelia", deparmentService.getDepartmentById(19)));
			cities.add(new City(62,"Argelia", deparmentService.getDepartmentById(76)));
			cities.add(new City(63,"Ariguaní (El Difícil)", deparmentService.getDepartmentById(47)));
			cities.add(new City(64,"Arjona", deparmentService.getDepartmentById(13)));
			cities.add(new City(65,"Armenia", deparmentService.getDepartmentById(5)));
			cities.add(new City(66,"Armenia", deparmentService.getDepartmentById(63)));
			cities.add(new City(67,"Armero (Guayabal)", deparmentService.getDepartmentById(73)));
			cities.add(new City(68,"Arroyohondo", deparmentService.getDepartmentById(13)));
			cities.add(new City(69,"Astrea", deparmentService.getDepartmentById(20)));
			cities.add(new City(70,"Ataco", deparmentService.getDepartmentById(73)));
			cities.add(new City(71,"Atrato (Yuto)", deparmentService.getDepartmentById(27)));
			cities.add(new City(72,"Ayapel", deparmentService.getDepartmentById(23)));
			cities.add(new City(73,"Bagadó", deparmentService.getDepartmentById(27)));
			cities.add(new City(74,"Bahía Solano (Mútis)", deparmentService.getDepartmentById(27)));
			cities.add(new City(75,"Bajo Baudó (Pizarro)", deparmentService.getDepartmentById(27)));
			cities.add(new City(76,"Balboa", deparmentService.getDepartmentById(19)));
			cities.add(new City(77,"Balboa", deparmentService.getDepartmentById(66)));
			cities.add(new City(78,"Baranoa", deparmentService.getDepartmentById(8)));
			cities.add(new City(79,"Baraya", deparmentService.getDepartmentById(41)));
			cities.add(new City(80,"Barbacoas", deparmentService.getDepartmentById(52)));
			cities.add(new City(81,"Barbosa", deparmentService.getDepartmentById(5)));
			cities.add(new City(82,"Barbosa", deparmentService.getDepartmentById(68)));
			cities.add(new City(83,"Barichara", deparmentService.getDepartmentById(68)));
			cities.add(new City(84,"Barranca de Upía", deparmentService.getDepartmentById(50)));
			cities.add(new City(85,"Barrancabermeja", deparmentService.getDepartmentById(68)));
			cities.add(new City(86,"Barrancas", deparmentService.getDepartmentById(44)));
			cities.add(new City(87,"Barranco de Loba", deparmentService.getDepartmentById(13)));
			cities.add(new City(88,"Barranquilla", deparmentService.getDepartmentById(8)));
			cities.add(new City(89,"Becerríl", deparmentService.getDepartmentById(20)));
			cities.add(new City(90,"Belalcázar", deparmentService.getDepartmentById(17)));
			cities.add(new City(91,"Bello", deparmentService.getDepartmentById(5)));
			cities.add(new City(92,"Belmira", deparmentService.getDepartmentById(5)));
			cities.add(new City(93,"Beltrán", deparmentService.getDepartmentById(25)));
			cities.add(new City(94,"Belén", deparmentService.getDepartmentById(15)));
			cities.add(new City(95,"Belén", deparmentService.getDepartmentById(52)));
			cities.add(new City(96,"Belén de Bajirá", deparmentService.getDepartmentById(27)));
			cities.add(new City(97,"Belén de Umbría", deparmentService.getDepartmentById(66)));
			cities.add(new City(98,"Belén de los Andaquíes", deparmentService.getDepartmentById(18)));
			cities.add(new City(99,"Berbeo", deparmentService.getDepartmentById(15)));
			cities.add(new City(100,"Betania", deparmentService.getDepartmentById(5)));
			cities.add(new City(101,"Beteitiva", deparmentService.getDepartmentById(15)));
			cities.add(new City(102,"Betulia", deparmentService.getDepartmentById(5)));
			cities.add(new City(103,"Betulia", deparmentService.getDepartmentById(68)));
			cities.add(new City(104,"Bituima", deparmentService.getDepartmentById(25)));
			cities.add(new City(105,"Boavita", deparmentService.getDepartmentById(15)));
			cities.add(new City(106,"Bochalema", deparmentService.getDepartmentById(54)));
			cities.add(new City(107,"Bogotá D.C.", deparmentService.getDepartmentById(11)));
			cities.add(new City(108,"Bojacá", deparmentService.getDepartmentById(25)));
			cities.add(new City(109,"Bojayá (Bellavista)", deparmentService.getDepartmentById(27)));
			cities.add(new City(110,"Bolívar", deparmentService.getDepartmentById(5)));
			cities.add(new City(111,"Bolívar", deparmentService.getDepartmentById(19)));
			cities.add(new City(112,"Bolívar", deparmentService.getDepartmentById(68)));
			cities.add(new City(113,"Bolívar", deparmentService.getDepartmentById(76)));
			cities.add(new City(114,"Bosconia", deparmentService.getDepartmentById(20)));
			cities.add(new City(115,"Boyacá", deparmentService.getDepartmentById(15)));
			cities.add(new City(116,"Briceño", deparmentService.getDepartmentById(5)));
			cities.add(new City(117,"Briceño", deparmentService.getDepartmentById(15)));
			cities.add(new City(118,"Bucaramanga", deparmentService.getDepartmentById(68)));
			cities.add(new City(119,"Bucarasica", deparmentService.getDepartmentById(54)));
			cities.add(new City(120,"Buenaventura", deparmentService.getDepartmentById(76)));
			cities.add(new City(121,"Buenavista", deparmentService.getDepartmentById(15)));
			cities.add(new City(122,"Buenavista", deparmentService.getDepartmentById(23)));
			cities.add(new City(123,"Buenavista", deparmentService.getDepartmentById(63)));
			cities.add(new City(124,"Buenavista", deparmentService.getDepartmentById(70)));
			cities.add(new City(125,"Buenos Aires", deparmentService.getDepartmentById(19)));
			cities.add(new City(126,"Buesaco", deparmentService.getDepartmentById(52)));
			cities.add(new City(127,"Buga", deparmentService.getDepartmentById(76)));
			cities.add(new City(128,"Bugalagrande", deparmentService.getDepartmentById(76)));
			cities.add(new City(129,"Burítica", deparmentService.getDepartmentById(5)));
			cities.add(new City(130,"Busbanza", deparmentService.getDepartmentById(15)));
			cities.add(new City(131,"Cabrera", deparmentService.getDepartmentById(25)));
			cities.add(new City(132,"Cabrera", deparmentService.getDepartmentById(68)));
			cities.add(new City(133,"Cabuyaro", deparmentService.getDepartmentById(50)));
			cities.add(new City(134,"Cachipay", deparmentService.getDepartmentById(25)));
			cities.add(new City(135,"Caicedo", deparmentService.getDepartmentById(5)));
			cities.add(new City(136,"Caicedonia", deparmentService.getDepartmentById(76)));
			cities.add(new City(137,"Caimito", deparmentService.getDepartmentById(70)));
			cities.add(new City(138,"Cajamarca", deparmentService.getDepartmentById(73)));
			cities.add(new City(139,"Cajibío", deparmentService.getDepartmentById(19)));
			cities.add(new City(140,"Cajicá", deparmentService.getDepartmentById(25)));
			cities.add(new City(141,"Calamar", deparmentService.getDepartmentById(13)));
			cities.add(new City(142,"Calamar", deparmentService.getDepartmentById(95)));
			cities.add(new City(143,"Calarcá", deparmentService.getDepartmentById(63)));
			cities.add(new City(144,"Caldas", deparmentService.getDepartmentById(5)));
			cities.add(new City(145,"Caldas", deparmentService.getDepartmentById(15)));
			cities.add(new City(146,"Caldono", deparmentService.getDepartmentById(19)));
			cities.add(new City(147,"California", deparmentService.getDepartmentById(68)));
			cities.add(new City(148,"Calima (Darién)", deparmentService.getDepartmentById(76)));
			cities.add(new City(149,"Caloto", deparmentService.getDepartmentById(19)));
			cities.add(new City(150,"Calí", deparmentService.getDepartmentById(76)));
			cities.add(new City(151,"Campamento", deparmentService.getDepartmentById(5)));
			cities.add(new City(152,"Campo de la Cruz", deparmentService.getDepartmentById(8)));
			cities.add(new City(153,"Campoalegre", deparmentService.getDepartmentById(41)));
			cities.add(new City(154,"Campohermoso", deparmentService.getDepartmentById(15)));
			cities.add(new City(155,"Canalete", deparmentService.getDepartmentById(23)));
			cities.add(new City(156,"Candelaria", deparmentService.getDepartmentById(8)));
			cities.add(new City(157,"Candelaria", deparmentService.getDepartmentById(76)));
			cities.add(new City(158,"Cantagallo", deparmentService.getDepartmentById(13)));
			cities.add(new City(159,"Cantón de San Pablo", deparmentService.getDepartmentById(27)));
			cities.add(new City(160,"Caparrapí", deparmentService.getDepartmentById(25)));
			cities.add(new City(161,"Capitanejo", deparmentService.getDepartmentById(68)));
			cities.add(new City(162,"Caracolí", deparmentService.getDepartmentById(5)));
			cities.add(new City(163,"Caramanta", deparmentService.getDepartmentById(5)));
			cities.add(new City(164,"Carcasí", deparmentService.getDepartmentById(68)));
			cities.add(new City(165,"Carepa", deparmentService.getDepartmentById(5)));
			cities.add(new City(166,"Carmen de Apicalá", deparmentService.getDepartmentById(73)));
			cities.add(new City(167,"Carmen de Carupa", deparmentService.getDepartmentById(25)));
			cities.add(new City(168,"Carmen de Viboral", deparmentService.getDepartmentById(5)));
			cities.add(new City(169,"Carmen del Darién (CURBARADÓ)", deparmentService.getDepartmentById(27)));
			cities.add(new City(170,"Carolina", deparmentService.getDepartmentById(5)));
			cities.add(new City(171,"Cartagena", deparmentService.getDepartmentById(13)));
			cities.add(new City(172,"Cartagena del Chairá", deparmentService.getDepartmentById(18)));
			cities.add(new City(173,"Cartago", deparmentService.getDepartmentById(76)));
			cities.add(new City(174,"Carurú", deparmentService.getDepartmentById(97)));
			cities.add(new City(175,"Casabianca", deparmentService.getDepartmentById(73)));
			cities.add(new City(176,"Castilla la Nueva", deparmentService.getDepartmentById(50)));
			cities.add(new City(177,"Caucasia", deparmentService.getDepartmentById(5)));
			cities.add(new City(178,"Cañasgordas", deparmentService.getDepartmentById(5)));
			cities.add(new City(179,"Cepita", deparmentService.getDepartmentById(68)));
			cities.add(new City(180,"Cereté", deparmentService.getDepartmentById(23)));
			cities.add(new City(181,"Cerinza", deparmentService.getDepartmentById(15)));
			cities.add(new City(182,"Cerrito", deparmentService.getDepartmentById(68)));
			cities.add(new City(183,"Cerro San Antonio", deparmentService.getDepartmentById(47)));
			cities.add(new City(184,"Chachaguí", deparmentService.getDepartmentById(52)));
			cities.add(new City(185,"Chaguaní", deparmentService.getDepartmentById(25)));
			cities.add(new City(186,"Chalán", deparmentService.getDepartmentById(70)));
			cities.add(new City(187,"Chaparral", deparmentService.getDepartmentById(73)));
			cities.add(new City(188,"Charalá", deparmentService.getDepartmentById(68)));
			cities.add(new City(189,"Charta", deparmentService.getDepartmentById(68)));
			cities.add(new City(190,"Chigorodó", deparmentService.getDepartmentById(5)));
			cities.add(new City(191,"Chima", deparmentService.getDepartmentById(68)));
			cities.add(new City(192,"Chimichagua", deparmentService.getDepartmentById(20)));
			cities.add(new City(193,"Chimá", deparmentService.getDepartmentById(23)));
			cities.add(new City(194,"Chinavita", deparmentService.getDepartmentById(15)));
			cities.add(new City(195,"Chinchiná", deparmentService.getDepartmentById(17)));
			cities.add(new City(196,"Chinácota", deparmentService.getDepartmentById(54)));
			cities.add(new City(197,"Chinú", deparmentService.getDepartmentById(23)));
			cities.add(new City(198,"Chipaque", deparmentService.getDepartmentById(25)));
			cities.add(new City(199,"Chipatá", deparmentService.getDepartmentById(68)));
			cities.add(new City(200,"Chiquinquirá", deparmentService.getDepartmentById(15)));
			cities.add(new City(201,"Chiriguaná", deparmentService.getDepartmentById(20)));
			cities.add(new City(202,"Chiscas", deparmentService.getDepartmentById(15)));
			cities.add(new City(203,"Chita", deparmentService.getDepartmentById(15)));
			cities.add(new City(204,"Chitagá", deparmentService.getDepartmentById(54)));
			cities.add(new City(205,"Chitaraque", deparmentService.getDepartmentById(15)));
			cities.add(new City(206,"Chivatá", deparmentService.getDepartmentById(15)));
			cities.add(new City(207,"Chivolo", deparmentService.getDepartmentById(47)));
			cities.add(new City(208,"Choachí", deparmentService.getDepartmentById(25)));
			cities.add(new City(209,"Chocontá", deparmentService.getDepartmentById(25)));
			cities.add(new City(210,"Chámeza", deparmentService.getDepartmentById(85)));
			cities.add(new City(211,"Chía", deparmentService.getDepartmentById(25)));
			cities.add(new City(212,"Chíquiza", deparmentService.getDepartmentById(15)));
			cities.add(new City(213,"Chívor", deparmentService.getDepartmentById(15)));
			cities.add(new City(214,"Cicuco", deparmentService.getDepartmentById(13)));
			cities.add(new City(215,"Cimitarra", deparmentService.getDepartmentById(68)));
			cities.add(new City(216,"Circasia", deparmentService.getDepartmentById(63)));
			cities.add(new City(217,"Cisneros", deparmentService.getDepartmentById(5)));
			cities.add(new City(218,"Ciénaga", deparmentService.getDepartmentById(15)));
			cities.add(new City(219,"Ciénaga", deparmentService.getDepartmentById(47)));
			cities.add(new City(220,"Ciénaga de Oro", deparmentService.getDepartmentById(23)));
			cities.add(new City(221,"Clemencia", deparmentService.getDepartmentById(13)));
			cities.add(new City(222,"Cocorná", deparmentService.getDepartmentById(5)));
			cities.add(new City(223,"Coello", deparmentService.getDepartmentById(73)));
			cities.add(new City(224,"Cogua", deparmentService.getDepartmentById(25)));
			cities.add(new City(225,"Colombia", deparmentService.getDepartmentById(41)));
			cities.add(new City(226,"Colosó (Ricaurte)", deparmentService.getDepartmentById(70)));
			cities.add(new City(227,"Colón", deparmentService.getDepartmentById(86)));
			cities.add(new City(228,"Colón (Génova)", deparmentService.getDepartmentById(52)));
			cities.add(new City(229,"Concepción", deparmentService.getDepartmentById(5)));
			cities.add(new City(230,"Concepción", deparmentService.getDepartmentById(68)));
			cities.add(new City(231,"Concordia", deparmentService.getDepartmentById(5)));
			cities.add(new City(232,"Concordia", deparmentService.getDepartmentById(47)));
			cities.add(new City(233,"Condoto", deparmentService.getDepartmentById(27)));
			cities.add(new City(234,"Confines", deparmentService.getDepartmentById(68)));
			cities.add(new City(235,"Consaca", deparmentService.getDepartmentById(52)));
			cities.add(new City(236,"Contadero", deparmentService.getDepartmentById(52)));
			cities.add(new City(237,"Contratación", deparmentService.getDepartmentById(68)));
			cities.add(new City(238,"Convención", deparmentService.getDepartmentById(54)));
			cities.add(new City(239,"Copacabana", deparmentService.getDepartmentById(5)));
			cities.add(new City(240,"Coper", deparmentService.getDepartmentById(15)));
			cities.add(new City(241,"Cordobá", deparmentService.getDepartmentById(63)));
			cities.add(new City(242,"Corinto", deparmentService.getDepartmentById(19)));
			cities.add(new City(243,"Coromoro", deparmentService.getDepartmentById(68)));
			cities.add(new City(244,"Corozal", deparmentService.getDepartmentById(70)));
			cities.add(new City(245,"Corrales", deparmentService.getDepartmentById(15)));
			cities.add(new City(246,"Cota", deparmentService.getDepartmentById(25)));
			cities.add(new City(247,"Cotorra", deparmentService.getDepartmentById(23)));
			cities.add(new City(248,"Covarachía", deparmentService.getDepartmentById(15)));
			cities.add(new City(249,"Coveñas", deparmentService.getDepartmentById(70)));
			cities.add(new City(250,"Coyaima", deparmentService.getDepartmentById(73)));
			cities.add(new City(251,"Cravo Norte", deparmentService.getDepartmentById(81)));
			cities.add(new City(252,"Cuaspud (Carlosama)", deparmentService.getDepartmentById(52)));
			cities.add(new City(253,"Cubarral", deparmentService.getDepartmentById(50)));
			cities.add(new City(254,"Cubará", deparmentService.getDepartmentById(15)));
			cities.add(new City(255,"Cucaita", deparmentService.getDepartmentById(15)));
			cities.add(new City(256,"Cucunubá", deparmentService.getDepartmentById(25)));
			cities.add(new City(257,"Cucutilla", deparmentService.getDepartmentById(54)));
			cities.add(new City(258,"Cuitiva", deparmentService.getDepartmentById(15)));
			cities.add(new City(259,"Cumaral", deparmentService.getDepartmentById(50)));
			cities.add(new City(260,"Cumaribo", deparmentService.getDepartmentById(99)));
			cities.add(new City(261,"Cumbal", deparmentService.getDepartmentById(52)));
			cities.add(new City(262,"Cumbitara", deparmentService.getDepartmentById(52)));
			cities.add(new City(263,"Cunday", deparmentService.getDepartmentById(73)));
			cities.add(new City(264,"Curillo", deparmentService.getDepartmentById(18)));
			cities.add(new City(265,"Curití", deparmentService.getDepartmentById(68)));
			cities.add(new City(266,"Curumaní", deparmentService.getDepartmentById(20)));
			cities.add(new City(267,"Cáceres", deparmentService.getDepartmentById(5)));
			cities.add(new City(268,"Cáchira", deparmentService.getDepartmentById(54)));
			cities.add(new City(269,"Cácota", deparmentService.getDepartmentById(54)));
			cities.add(new City(270,"Cáqueza", deparmentService.getDepartmentById(25)));
			cities.add(new City(271,"Cértegui", deparmentService.getDepartmentById(27)));
			cities.add(new City(272,"Cómbita", deparmentService.getDepartmentById(15)));
			cities.add(new City(273,"Córdoba", deparmentService.getDepartmentById(13)));
			cities.add(new City(274,"Córdoba", deparmentService.getDepartmentById(52)));
			cities.add(new City(275,"Cúcuta", deparmentService.getDepartmentById(54)));
			cities.add(new City(276,"Dabeiba", deparmentService.getDepartmentById(5)));
			cities.add(new City(277,"Dagua", deparmentService.getDepartmentById(76)));
			cities.add(new City(278,"Dibulla", deparmentService.getDepartmentById(44)));
			cities.add(new City(279,"Distracción", deparmentService.getDepartmentById(44)));
			cities.add(new City(280,"Dolores", deparmentService.getDepartmentById(73)));
			cities.add(new City(281,"Don Matías", deparmentService.getDepartmentById(5)));
			cities.add(new City(282,"Dos Quebradas", deparmentService.getDepartmentById(66)));
			cities.add(new City(283,"Duitama", deparmentService.getDepartmentById(15)));
			cities.add(new City(284,"Durania", deparmentService.getDepartmentById(54)));
			cities.add(new City(285,"Ebéjico", deparmentService.getDepartmentById(5)));
			cities.add(new City(286,"El Bagre", deparmentService.getDepartmentById(5)));
			cities.add(new City(287,"El Banco", deparmentService.getDepartmentById(47)));
			cities.add(new City(288,"El Cairo", deparmentService.getDepartmentById(76)));
			cities.add(new City(289,"El Calvario", deparmentService.getDepartmentById(50)));
			cities.add(new City(290,"El Carmen", deparmentService.getDepartmentById(54)));
			cities.add(new City(291,"El Carmen", deparmentService.getDepartmentById(68)));
			cities.add(new City(292,"El Carmen de Atrato", deparmentService.getDepartmentById(27)));
			cities.add(new City(293,"El Carmen de Bolívar", deparmentService.getDepartmentById(13)));
			cities.add(new City(294,"El Castillo", deparmentService.getDepartmentById(50)));
			cities.add(new City(295,"El Cerrito", deparmentService.getDepartmentById(76)));
			cities.add(new City(296,"El Charco", deparmentService.getDepartmentById(52)));
			cities.add(new City(297,"El Cocuy", deparmentService.getDepartmentById(15)));
			cities.add(new City(298,"El Colegio", deparmentService.getDepartmentById(25)));
			cities.add(new City(299,"El Copey", deparmentService.getDepartmentById(20)));
			cities.add(new City(300,"El Doncello", deparmentService.getDepartmentById(18)));
			cities.add(new City(301,"El Dorado", deparmentService.getDepartmentById(50)));
			cities.add(new City(302,"El Dovio", deparmentService.getDepartmentById(76)));
			cities.add(new City(303,"El Espino", deparmentService.getDepartmentById(15)));
			cities.add(new City(304,"El Guacamayo", deparmentService.getDepartmentById(68)));
			cities.add(new City(305,"El Guamo", deparmentService.getDepartmentById(13)));
			cities.add(new City(306,"El Molino", deparmentService.getDepartmentById(44)));
			cities.add(new City(307,"El Paso", deparmentService.getDepartmentById(20)));
			cities.add(new City(308,"El Paujil", deparmentService.getDepartmentById(18)));
			cities.add(new City(309,"El Peñol", deparmentService.getDepartmentById(52)));
			cities.add(new City(310,"El Peñon", deparmentService.getDepartmentById(13)));
			cities.add(new City(311,"El Peñon", deparmentService.getDepartmentById(68)));
			cities.add(new City(312,"El Peñón", deparmentService.getDepartmentById(25)));
			cities.add(new City(313,"El Piñon", deparmentService.getDepartmentById(47)));
			cities.add(new City(314,"El Playón", deparmentService.getDepartmentById(68)));
			cities.add(new City(315,"El Retorno", deparmentService.getDepartmentById(95)));
			cities.add(new City(316,"El Retén", deparmentService.getDepartmentById(47)));
			cities.add(new City(317,"El Roble", deparmentService.getDepartmentById(70)));
			cities.add(new City(318,"El Rosal", deparmentService.getDepartmentById(25)));
			cities.add(new City(319,"El Rosario", deparmentService.getDepartmentById(52)));
			cities.add(new City(320,"El Tablón de Gómez", deparmentService.getDepartmentById(52)));
			cities.add(new City(321,"El Tambo", deparmentService.getDepartmentById(19)));
			cities.add(new City(322,"El Tambo", deparmentService.getDepartmentById(52)));
			cities.add(new City(323,"El Tarra", deparmentService.getDepartmentById(54)));
			cities.add(new City(324,"El Zulia", deparmentService.getDepartmentById(54)));
			cities.add(new City(325,"El Águila", deparmentService.getDepartmentById(76)));
			cities.add(new City(326,"Elías", deparmentService.getDepartmentById(41)));
			cities.add(new City(327,"Encino", deparmentService.getDepartmentById(68)));
			cities.add(new City(328,"Enciso", deparmentService.getDepartmentById(68)));
			cities.add(new City(329,"Entrerríos", deparmentService.getDepartmentById(5)));
			cities.add(new City(330,"Envigado", deparmentService.getDepartmentById(5)));
			cities.add(new City(331,"Espinal", deparmentService.getDepartmentById(73)));
			cities.add(new City(332,"Facatativá", deparmentService.getDepartmentById(25)));
			cities.add(new City(333,"Falan", deparmentService.getDepartmentById(73)));
			cities.add(new City(334,"Filadelfia", deparmentService.getDepartmentById(17)));
			cities.add(new City(335,"Filandia", deparmentService.getDepartmentById(63)));
			cities.add(new City(336,"Firavitoba", deparmentService.getDepartmentById(15)));
			cities.add(new City(337,"Flandes", deparmentService.getDepartmentById(73)));
			cities.add(new City(338,"Florencia", deparmentService.getDepartmentById(18)));
			cities.add(new City(339,"Florencia", deparmentService.getDepartmentById(19)));
			cities.add(new City(340,"Floresta", deparmentService.getDepartmentById(15)));
			cities.add(new City(341,"Florida", deparmentService.getDepartmentById(76)));
			cities.add(new City(342,"Floridablanca", deparmentService.getDepartmentById(68)));
			cities.add(new City(343,"Florián", deparmentService.getDepartmentById(68)));
			cities.add(new City(344,"Fonseca", deparmentService.getDepartmentById(44)));
			cities.add(new City(345,"Fortúl", deparmentService.getDepartmentById(81)));
			cities.add(new City(346,"Fosca", deparmentService.getDepartmentById(25)));
			cities.add(new City(347,"Francisco Pizarro", deparmentService.getDepartmentById(52)));
			cities.add(new City(348,"Fredonia", deparmentService.getDepartmentById(5)));
			cities.add(new City(349,"Fresno", deparmentService.getDepartmentById(73)));
			cities.add(new City(350,"Frontino", deparmentService.getDepartmentById(5)));
			cities.add(new City(351,"Fuente de Oro", deparmentService.getDepartmentById(50)));
			cities.add(new City(352,"Fundación", deparmentService.getDepartmentById(47)));
			cities.add(new City(353,"Funes", deparmentService.getDepartmentById(52)));
			cities.add(new City(354,"Funza", deparmentService.getDepartmentById(25)));
			cities.add(new City(355,"Fusagasugá", deparmentService.getDepartmentById(25)));
			cities.add(new City(356,"Fómeque", deparmentService.getDepartmentById(25)));
			cities.add(new City(357,"Fúquene", deparmentService.getDepartmentById(25)));
			cities.add(new City(358,"Gachalá", deparmentService.getDepartmentById(25)));
			cities.add(new City(359,"Gachancipá", deparmentService.getDepartmentById(25)));
			cities.add(new City(360,"Gachantivá", deparmentService.getDepartmentById(15)));
			cities.add(new City(361,"Gachetá", deparmentService.getDepartmentById(25)));
			cities.add(new City(362,"Galapa", deparmentService.getDepartmentById(8)));
			cities.add(new City(363,"Galeras (Nueva Granada)", deparmentService.getDepartmentById(70)));
			cities.add(new City(364,"Galán", deparmentService.getDepartmentById(68)));
			cities.add(new City(365,"Gama", deparmentService.getDepartmentById(25)));
			cities.add(new City(366,"Gamarra", deparmentService.getDepartmentById(20)));
			cities.add(new City(367,"Garagoa", deparmentService.getDepartmentById(15)));
			cities.add(new City(368,"Garzón", deparmentService.getDepartmentById(41)));
			cities.add(new City(369,"Gigante", deparmentService.getDepartmentById(41)));
			cities.add(new City(370,"Ginebra", deparmentService.getDepartmentById(76)));
			cities.add(new City(371,"Giraldo", deparmentService.getDepartmentById(5)));
			cities.add(new City(372,"Girardot", deparmentService.getDepartmentById(25)));
			cities.add(new City(373,"Girardota", deparmentService.getDepartmentById(5)));
			cities.add(new City(374,"Girón", deparmentService.getDepartmentById(68)));
			cities.add(new City(375,"Gonzalez", deparmentService.getDepartmentById(20)));
			cities.add(new City(376,"Gramalote", deparmentService.getDepartmentById(54)));
			cities.add(new City(377,"Granada", deparmentService.getDepartmentById(5)));
			cities.add(new City(378,"Granada", deparmentService.getDepartmentById(25)));
			cities.add(new City(379,"Granada", deparmentService.getDepartmentById(50)));
			cities.add(new City(380,"Guaca", deparmentService.getDepartmentById(68)));
			cities.add(new City(381,"Guacamayas", deparmentService.getDepartmentById(15)));
			cities.add(new City(382,"Guacarí", deparmentService.getDepartmentById(76)));
			cities.add(new City(383,"Guachavés", deparmentService.getDepartmentById(52)));
			cities.add(new City(384,"Guachené", deparmentService.getDepartmentById(19)));
			cities.add(new City(385,"Guachetá", deparmentService.getDepartmentById(25)));
			cities.add(new City(386,"Guachucal", deparmentService.getDepartmentById(52)));
			cities.add(new City(387,"Guadalupe", deparmentService.getDepartmentById(5)));
			cities.add(new City(388,"Guadalupe", deparmentService.getDepartmentById(41)));
			cities.add(new City(389,"Guadalupe", deparmentService.getDepartmentById(68)));
			cities.add(new City(390,"Guaduas", deparmentService.getDepartmentById(25)));
			cities.add(new City(391,"Guaitarilla", deparmentService.getDepartmentById(52)));
			cities.add(new City(392,"Gualmatán", deparmentService.getDepartmentById(52)));
			cities.add(new City(393,"Guamal", deparmentService.getDepartmentById(47)));
			cities.add(new City(394,"Guamal", deparmentService.getDepartmentById(50)));
			cities.add(new City(395,"Guamo", deparmentService.getDepartmentById(73)));
			cities.add(new City(396,"Guapota", deparmentService.getDepartmentById(68)));
			cities.add(new City(397,"Guapí", deparmentService.getDepartmentById(19)));
			cities.add(new City(398,"Guaranda", deparmentService.getDepartmentById(70)));
			cities.add(new City(399,"Guarne", deparmentService.getDepartmentById(5)));
			cities.add(new City(400,"Guasca", deparmentService.getDepartmentById(25)));
			cities.add(new City(401,"Guatapé", deparmentService.getDepartmentById(5)));
			cities.add(new City(402,"Guataquí", deparmentService.getDepartmentById(25)));
			cities.add(new City(403,"Guatavita", deparmentService.getDepartmentById(25)));
			cities.add(new City(404,"Guateque", deparmentService.getDepartmentById(15)));
			cities.add(new City(405,"Guavatá", deparmentService.getDepartmentById(68)));
			cities.add(new City(406,"Guayabal de Siquima", deparmentService.getDepartmentById(25)));
			cities.add(new City(407,"Guayabetal", deparmentService.getDepartmentById(25)));
			cities.add(new City(408,"Guayatá", deparmentService.getDepartmentById(15)));
			cities.add(new City(409,"Guepsa", deparmentService.getDepartmentById(68)));
			cities.add(new City(410,"Guicán", deparmentService.getDepartmentById(15)));
			cities.add(new City(411,"Gutiérrez", deparmentService.getDepartmentById(25)));
			cities.add(new City(412,"Guática", deparmentService.getDepartmentById(66)));
			cities.add(new City(413,"Gámbita", deparmentService.getDepartmentById(68)));
			cities.add(new City(414,"Gámeza", deparmentService.getDepartmentById(15)));
			cities.add(new City(415,"Génova", deparmentService.getDepartmentById(63)));
			cities.add(new City(416,"Gómez Plata", deparmentService.getDepartmentById(5)));
			cities.add(new City(417,"Hacarí", deparmentService.getDepartmentById(54)));
			cities.add(new City(418,"Hatillo de Loba", deparmentService.getDepartmentById(13)));
			cities.add(new City(419,"Hato", deparmentService.getDepartmentById(68)));
			cities.add(new City(420,"Hato Corozal", deparmentService.getDepartmentById(85)));
			cities.add(new City(421,"Hatonuevo", deparmentService.getDepartmentById(44)));
			cities.add(new City(422,"Heliconia", deparmentService.getDepartmentById(5)));
			cities.add(new City(423,"Herrán", deparmentService.getDepartmentById(54)));
			cities.add(new City(424,"Herveo", deparmentService.getDepartmentById(73)));
			cities.add(new City(425,"Hispania", deparmentService.getDepartmentById(5)));
			cities.add(new City(426,"Hobo", deparmentService.getDepartmentById(41)));
			cities.add(new City(427,"Honda", deparmentService.getDepartmentById(73)));
			cities.add(new City(428,"Ibagué", deparmentService.getDepartmentById(73)));
			cities.add(new City(429,"Icononzo", deparmentService.getDepartmentById(73)));
			cities.add(new City(430,"Iles", deparmentService.getDepartmentById(52)));
			cities.add(new City(431,"Imúes", deparmentService.getDepartmentById(52)));
			cities.add(new City(432,"Inzá", deparmentService.getDepartmentById(19)));
			cities.add(new City(433,"Inírida", deparmentService.getDepartmentById(94)));
			cities.add(new City(434,"Ipiales", deparmentService.getDepartmentById(52)));
			cities.add(new City(435,"Isnos", deparmentService.getDepartmentById(41)));
			cities.add(new City(436,"Istmina", deparmentService.getDepartmentById(27)));
			cities.add(new City(437,"Itagüí", deparmentService.getDepartmentById(5)));
			cities.add(new City(438,"Ituango", deparmentService.getDepartmentById(5)));
			cities.add(new City(439,"Izá", deparmentService.getDepartmentById(15)));
			cities.add(new City(440,"Jambaló", deparmentService.getDepartmentById(19)));
			cities.add(new City(441,"Jamundí", deparmentService.getDepartmentById(76)));
			cities.add(new City(442,"Jardín", deparmentService.getDepartmentById(5)));
			cities.add(new City(443,"Jenesano", deparmentService.getDepartmentById(15)));
			cities.add(new City(444,"Jericó", deparmentService.getDepartmentById(5)));
			cities.add(new City(445,"Jericó", deparmentService.getDepartmentById(15)));
			cities.add(new City(446,"Jerusalén", deparmentService.getDepartmentById(25)));
			cities.add(new City(447,"Jesús María", deparmentService.getDepartmentById(68)));
			cities.add(new City(448,"Jordán", deparmentService.getDepartmentById(68)));
			cities.add(new City(449,"Juan de Acosta", deparmentService.getDepartmentById(8)));
			cities.add(new City(450,"Junín", deparmentService.getDepartmentById(25)));
			cities.add(new City(451,"Juradó", deparmentService.getDepartmentById(27)));
			cities.add(new City(452,"La Apartada y La Frontera", deparmentService.getDepartmentById(23)));
			cities.add(new City(453,"La Argentina", deparmentService.getDepartmentById(41)));
			cities.add(new City(454,"La Belleza", deparmentService.getDepartmentById(68)));
			cities.add(new City(455,"La Calera", deparmentService.getDepartmentById(25)));
			cities.add(new City(456,"La Capilla", deparmentService.getDepartmentById(15)));
			cities.add(new City(457,"La Ceja", deparmentService.getDepartmentById(5)));
			cities.add(new City(458,"La Celia", deparmentService.getDepartmentById(66)));
			cities.add(new City(459,"La Cruz", deparmentService.getDepartmentById(52)));
			cities.add(new City(460,"La Cumbre", deparmentService.getDepartmentById(76)));
			cities.add(new City(461,"La Dorada", deparmentService.getDepartmentById(17)));
			cities.add(new City(462,"La Esperanza", deparmentService.getDepartmentById(54)));
			cities.add(new City(463,"La Estrella", deparmentService.getDepartmentById(5)));
			cities.add(new City(464,"La Florida", deparmentService.getDepartmentById(52)));
			cities.add(new City(465,"La Gloria", deparmentService.getDepartmentById(20)));
			cities.add(new City(466,"La Jagua de Ibirico", deparmentService.getDepartmentById(20)));
			cities.add(new City(467,"La Jagua del Pilar", deparmentService.getDepartmentById(44)));
			cities.add(new City(468,"La Llanada", deparmentService.getDepartmentById(52)));
			cities.add(new City(469,"La Macarena", deparmentService.getDepartmentById(50)));
			cities.add(new City(470,"La Merced", deparmentService.getDepartmentById(17)));
			cities.add(new City(471,"La Mesa", deparmentService.getDepartmentById(25)));
			cities.add(new City(472,"La Montañita", deparmentService.getDepartmentById(18)));
			cities.add(new City(473,"La Palma", deparmentService.getDepartmentById(25)));
			cities.add(new City(474,"La Paz", deparmentService.getDepartmentById(68)));
			cities.add(new City(475,"La Paz (Robles)", deparmentService.getDepartmentById(20)));
			cities.add(new City(476,"La Peña", deparmentService.getDepartmentById(25)));
			cities.add(new City(477,"La Pintada", deparmentService.getDepartmentById(5)));
			cities.add(new City(478,"La Plata", deparmentService.getDepartmentById(41)));
			cities.add(new City(479,"La Playa", deparmentService.getDepartmentById(54)));
			cities.add(new City(480,"La Primavera", deparmentService.getDepartmentById(99)));
			cities.add(new City(481,"La Salina", deparmentService.getDepartmentById(85)));
			cities.add(new City(482,"La Sierra", deparmentService.getDepartmentById(19)));
			cities.add(new City(483,"La Tebaida", deparmentService.getDepartmentById(63)));
			cities.add(new City(484,"La Tola", deparmentService.getDepartmentById(52)));
			cities.add(new City(485,"La Unión", deparmentService.getDepartmentById(5)));
			cities.add(new City(486,"La Unión", deparmentService.getDepartmentById(52)));
			cities.add(new City(487,"La Unión", deparmentService.getDepartmentById(70)));
			cities.add(new City(488,"La Unión", deparmentService.getDepartmentById(76)));
			cities.add(new City(489,"La Uvita", deparmentService.getDepartmentById(15)));
			cities.add(new City(490,"La Vega", deparmentService.getDepartmentById(19)));
			cities.add(new City(491,"La Vega", deparmentService.getDepartmentById(25)));
			cities.add(new City(492,"La Victoria", deparmentService.getDepartmentById(15)));
			cities.add(new City(493,"La Victoria", deparmentService.getDepartmentById(17)));
			cities.add(new City(494,"La Victoria", deparmentService.getDepartmentById(76)));
			cities.add(new City(495,"La Virginia", deparmentService.getDepartmentById(66)));
			cities.add(new City(496,"Labateca", deparmentService.getDepartmentById(54)));
			cities.add(new City(497,"Labranzagrande", deparmentService.getDepartmentById(15)));
			cities.add(new City(498,"Landázuri", deparmentService.getDepartmentById(68)));
			cities.add(new City(499,"Lebrija", deparmentService.getDepartmentById(68)));
			cities.add(new City(500,"Leiva", deparmentService.getDepartmentById(52)));
			cities.add(new City(501,"Lejanías", deparmentService.getDepartmentById(50)));
			cities.add(new City(502,"Lenguazaque", deparmentService.getDepartmentById(25)));
			cities.add(new City(503,"Leticia", deparmentService.getDepartmentById(91)));
			cities.add(new City(504,"Liborina", deparmentService.getDepartmentById(5)));
			cities.add(new City(505,"Linares", deparmentService.getDepartmentById(52)));
			cities.add(new City(506,"Lloró", deparmentService.getDepartmentById(27)));
			cities.add(new City(507,"Lorica", deparmentService.getDepartmentById(23)));
			cities.add(new City(508,"Los Córdobas", deparmentService.getDepartmentById(23)));
			cities.add(new City(509,"Los Palmitos", deparmentService.getDepartmentById(70)));
			cities.add(new City(510,"Los Patios", deparmentService.getDepartmentById(54)));
			cities.add(new City(511,"Los Santos", deparmentService.getDepartmentById(68)));
			cities.add(new City(512,"Lourdes", deparmentService.getDepartmentById(54)));
			cities.add(new City(513,"Luruaco", deparmentService.getDepartmentById(8)));
			cities.add(new City(514,"Lérida", deparmentService.getDepartmentById(73)));
			cities.add(new City(515,"Líbano", deparmentService.getDepartmentById(73)));
			cities.add(new City(516,"López (Micay)", deparmentService.getDepartmentById(19)));
			cities.add(new City(517,"Macanal", deparmentService.getDepartmentById(15)));
			cities.add(new City(518,"Macaravita", deparmentService.getDepartmentById(68)));
			cities.add(new City(519,"Maceo", deparmentService.getDepartmentById(5)));
			cities.add(new City(520,"Machetá", deparmentService.getDepartmentById(25)));
			cities.add(new City(521,"Madrid", deparmentService.getDepartmentById(25)));
			cities.add(new City(522,"Magangué", deparmentService.getDepartmentById(13)));
			cities.add(new City(523,"Magüi (Payán)", deparmentService.getDepartmentById(52)));
			cities.add(new City(524,"Mahates", deparmentService.getDepartmentById(13)));
			cities.add(new City(525,"Maicao", deparmentService.getDepartmentById(44)));
			cities.add(new City(526,"Majagual", deparmentService.getDepartmentById(70)));
			cities.add(new City(527,"Malambo", deparmentService.getDepartmentById(8)));
			cities.add(new City(528,"Mallama (Piedrancha)", deparmentService.getDepartmentById(52)));
			cities.add(new City(529,"Manatí", deparmentService.getDepartmentById(8)));
			cities.add(new City(530,"Manaure", deparmentService.getDepartmentById(44)));
			cities.add(new City(531,"Manaure Balcón del Cesar", deparmentService.getDepartmentById(20)));
			cities.add(new City(532,"Manizales", deparmentService.getDepartmentById(17)));
			cities.add(new City(533,"Manta", deparmentService.getDepartmentById(25)));
			cities.add(new City(534,"Manzanares", deparmentService.getDepartmentById(17)));
			cities.add(new City(535,"Maní", deparmentService.getDepartmentById(85)));
			cities.add(new City(536,"Mapiripan", deparmentService.getDepartmentById(50)));
			cities.add(new City(537,"Margarita", deparmentService.getDepartmentById(13)));
			cities.add(new City(538,"Marinilla", deparmentService.getDepartmentById(5)));
			cities.add(new City(539,"Maripí", deparmentService.getDepartmentById(15)));
			cities.add(new City(540,"Mariquita", deparmentService.getDepartmentById(73)));
			cities.add(new City(541,"Marmato", deparmentService.getDepartmentById(17)));
			cities.add(new City(542,"Marquetalia", deparmentService.getDepartmentById(17)));
			cities.add(new City(543,"Marsella", deparmentService.getDepartmentById(66)));
			cities.add(new City(544,"Marulanda", deparmentService.getDepartmentById(17)));
			cities.add(new City(545,"María la Baja", deparmentService.getDepartmentById(13)));
			cities.add(new City(546,"Matanza", deparmentService.getDepartmentById(68)));
			cities.add(new City(547,"Medellín", deparmentService.getDepartmentById(5)));
			cities.add(new City(548,"Medina", deparmentService.getDepartmentById(25)));
			cities.add(new City(549,"Medio Atrato", deparmentService.getDepartmentById(27)));
			cities.add(new City(550,"Medio Baudó", deparmentService.getDepartmentById(27)));
			cities.add(new City(551,"Medio San Juan (ANDAGOYA)", deparmentService.getDepartmentById(27)));
			cities.add(new City(552,"Melgar", deparmentService.getDepartmentById(73)));
			cities.add(new City(553,"Mercaderes", deparmentService.getDepartmentById(19)));
			cities.add(new City(554,"Mesetas", deparmentService.getDepartmentById(50)));
			cities.add(new City(555,"Milán", deparmentService.getDepartmentById(18)));
			cities.add(new City(556,"Miraflores", deparmentService.getDepartmentById(15)));
			cities.add(new City(557,"Miraflores", deparmentService.getDepartmentById(95)));
			cities.add(new City(558,"Miranda", deparmentService.getDepartmentById(19)));
			cities.add(new City(559,"Mistrató", deparmentService.getDepartmentById(66)));
			cities.add(new City(560,"Mitú", deparmentService.getDepartmentById(97)));
			cities.add(new City(561,"Mocoa", deparmentService.getDepartmentById(86)));
			cities.add(new City(562,"Mogotes", deparmentService.getDepartmentById(68)));
			cities.add(new City(563,"Molagavita", deparmentService.getDepartmentById(68)));
			cities.add(new City(564,"Momil", deparmentService.getDepartmentById(23)));
			cities.add(new City(565,"Mompós", deparmentService.getDepartmentById(13)));
			cities.add(new City(566,"Mongua", deparmentService.getDepartmentById(15)));
			cities.add(new City(567,"Monguí", deparmentService.getDepartmentById(15)));
			cities.add(new City(568,"Moniquirá", deparmentService.getDepartmentById(15)));
			cities.add(new City(569,"Montebello", deparmentService.getDepartmentById(5)));
			cities.add(new City(570,"Montecristo", deparmentService.getDepartmentById(13)));
			cities.add(new City(571,"Montelíbano", deparmentService.getDepartmentById(23)));
			cities.add(new City(572,"Montenegro", deparmentService.getDepartmentById(63)));
			cities.add(new City(573,"Monteria", deparmentService.getDepartmentById(23)));
			cities.add(new City(574,"Monterrey", deparmentService.getDepartmentById(85)));
			cities.add(new City(575,"Morales", deparmentService.getDepartmentById(13)));
			cities.add(new City(576,"Morales", deparmentService.getDepartmentById(19)));
			cities.add(new City(577,"Morelia", deparmentService.getDepartmentById(18)));
			cities.add(new City(578,"Morroa", deparmentService.getDepartmentById(70)));
			cities.add(new City(579,"Mosquera", deparmentService.getDepartmentById(25)));
			cities.add(new City(580,"Mosquera", deparmentService.getDepartmentById(52)));
			cities.add(new City(581,"Motavita", deparmentService.getDepartmentById(15)));
			cities.add(new City(582,"Moñitos", deparmentService.getDepartmentById(23)));
			cities.add(new City(583,"Murillo", deparmentService.getDepartmentById(73)));
			cities.add(new City(584,"Murindó", deparmentService.getDepartmentById(5)));
			cities.add(new City(585,"Mutatá", deparmentService.getDepartmentById(5)));
			cities.add(new City(586,"Mutiscua", deparmentService.getDepartmentById(54)));
			cities.add(new City(587,"Muzo", deparmentService.getDepartmentById(15)));
			cities.add(new City(588,"Málaga", deparmentService.getDepartmentById(68)));
			cities.add(new City(589,"Nariño", deparmentService.getDepartmentById(5)));
			cities.add(new City(590,"Nariño", deparmentService.getDepartmentById(25)));
			cities.add(new City(591,"Nariño", deparmentService.getDepartmentById(52)));
			cities.add(new City(592,"Natagaima", deparmentService.getDepartmentById(73)));
			cities.add(new City(593,"Nechí", deparmentService.getDepartmentById(5)));
			cities.add(new City(594,"Necoclí", deparmentService.getDepartmentById(5)));
			cities.add(new City(595,"Neira", deparmentService.getDepartmentById(17)));
			cities.add(new City(596,"Neiva", deparmentService.getDepartmentById(41)));
			cities.add(new City(597,"Nemocón", deparmentService.getDepartmentById(25)));
			cities.add(new City(598,"Nilo", deparmentService.getDepartmentById(25)));
			cities.add(new City(599,"Nimaima", deparmentService.getDepartmentById(25)));
			cities.add(new City(600,"Nobsa", deparmentService.getDepartmentById(15)));
			cities.add(new City(601,"Nocaima", deparmentService.getDepartmentById(25)));
			cities.add(new City(602,"Norcasia", deparmentService.getDepartmentById(17)));
			cities.add(new City(603,"Norosí", deparmentService.getDepartmentById(13)));
			cities.add(new City(604,"Novita", deparmentService.getDepartmentById(27)));
			cities.add(new City(605,"Nueva Granada", deparmentService.getDepartmentById(47)));
			cities.add(new City(606,"Nuevo Colón", deparmentService.getDepartmentById(15)));
			cities.add(new City(607,"Nunchía", deparmentService.getDepartmentById(85)));
			cities.add(new City(608,"Nuquí", deparmentService.getDepartmentById(27)));
			cities.add(new City(609,"Nátaga", deparmentService.getDepartmentById(41)));
			cities.add(new City(610,"Obando", deparmentService.getDepartmentById(76)));
			cities.add(new City(611,"Ocamonte", deparmentService.getDepartmentById(68)));
			cities.add(new City(612,"Ocaña", deparmentService.getDepartmentById(54)));
			cities.add(new City(613,"Oiba", deparmentService.getDepartmentById(68)));
			cities.add(new City(614,"Oicatá", deparmentService.getDepartmentById(15)));
			cities.add(new City(615,"Olaya", deparmentService.getDepartmentById(5)));
			cities.add(new City(616,"Olaya Herrera", deparmentService.getDepartmentById(52)));
			cities.add(new City(617,"Onzaga", deparmentService.getDepartmentById(68)));
			cities.add(new City(618,"Oporapa", deparmentService.getDepartmentById(41)));
			cities.add(new City(619,"Orito", deparmentService.getDepartmentById(86)));
			cities.add(new City(620,"Orocué", deparmentService.getDepartmentById(85)));
			cities.add(new City(621,"Ortega", deparmentService.getDepartmentById(73)));
			cities.add(new City(622,"Ospina", deparmentService.getDepartmentById(52)));
			cities.add(new City(623,"Otanche", deparmentService.getDepartmentById(15)));
			cities.add(new City(624,"Ovejas", deparmentService.getDepartmentById(70)));
			cities.add(new City(625,"Pachavita", deparmentService.getDepartmentById(15)));
			cities.add(new City(626,"Pacho", deparmentService.getDepartmentById(25)));
			cities.add(new City(627,"Padilla", deparmentService.getDepartmentById(19)));
			cities.add(new City(628,"Paicol", deparmentService.getDepartmentById(41)));
			cities.add(new City(629,"Pailitas", deparmentService.getDepartmentById(20)));
			cities.add(new City(630,"Paime", deparmentService.getDepartmentById(25)));
			cities.add(new City(631,"Paipa", deparmentService.getDepartmentById(15)));
			cities.add(new City(632,"Pajarito", deparmentService.getDepartmentById(15)));
			cities.add(new City(633,"Palermo", deparmentService.getDepartmentById(41)));
			cities.add(new City(634,"Palestina", deparmentService.getDepartmentById(17)));
			cities.add(new City(635,"Palestina", deparmentService.getDepartmentById(41)));
			cities.add(new City(636,"Palmar", deparmentService.getDepartmentById(68)));
			cities.add(new City(637,"Palmar de Varela", deparmentService.getDepartmentById(8)));
			cities.add(new City(638,"Palmas del Socorro", deparmentService.getDepartmentById(68)));
			cities.add(new City(639,"Palmira", deparmentService.getDepartmentById(76)));
			cities.add(new City(640,"Palmito", deparmentService.getDepartmentById(70)));
			cities.add(new City(641,"Palocabildo", deparmentService.getDepartmentById(73)));
			cities.add(new City(642,"Pamplona", deparmentService.getDepartmentById(54)));
			cities.add(new City(643,"Pamplonita", deparmentService.getDepartmentById(54)));
			cities.add(new City(644,"Pandi", deparmentService.getDepartmentById(25)));
			cities.add(new City(645,"Panqueba", deparmentService.getDepartmentById(15)));
			cities.add(new City(646,"Paratebueno", deparmentService.getDepartmentById(25)));
			cities.add(new City(647,"Pasca", deparmentService.getDepartmentById(25)));
			cities.add(new City(648,"Patía (El Bordo)", deparmentService.getDepartmentById(19)));
			cities.add(new City(649,"Pauna", deparmentService.getDepartmentById(15)));
			cities.add(new City(650,"Paya", deparmentService.getDepartmentById(15)));
			cities.add(new City(651,"Paz de Ariporo", deparmentService.getDepartmentById(85)));
			cities.add(new City(652,"Paz de Río", deparmentService.getDepartmentById(15)));
			cities.add(new City(653,"Pedraza", deparmentService.getDepartmentById(47)));
			cities.add(new City(654,"Pelaya", deparmentService.getDepartmentById(20)));
			cities.add(new City(655,"Pensilvania", deparmentService.getDepartmentById(17)));
			cities.add(new City(656,"Peque", deparmentService.getDepartmentById(5)));
			cities.add(new City(657,"Pereira", deparmentService.getDepartmentById(66)));
			cities.add(new City(658,"Pesca", deparmentService.getDepartmentById(15)));
			cities.add(new City(659,"Peñol", deparmentService.getDepartmentById(5)));
			cities.add(new City(660,"Piamonte", deparmentService.getDepartmentById(19)));
			cities.add(new City(661,"Pie de Cuesta", deparmentService.getDepartmentById(68)));
			cities.add(new City(662,"Piedras", deparmentService.getDepartmentById(73)));
			cities.add(new City(663,"Piendamó", deparmentService.getDepartmentById(19)));
			cities.add(new City(664,"Pijao", deparmentService.getDepartmentById(63)));
			cities.add(new City(665,"Pijiño", deparmentService.getDepartmentById(47)));
			cities.add(new City(666,"Pinchote", deparmentService.getDepartmentById(68)));
			cities.add(new City(667,"Pinillos", deparmentService.getDepartmentById(13)));
			cities.add(new City(668,"Piojo", deparmentService.getDepartmentById(8)));
			cities.add(new City(669,"Pisva", deparmentService.getDepartmentById(15)));
			cities.add(new City(670,"Pital", deparmentService.getDepartmentById(41)));
			cities.add(new City(671,"Pitalito", deparmentService.getDepartmentById(41)));
			cities.add(new City(672,"Pivijay", deparmentService.getDepartmentById(47)));
			cities.add(new City(673,"Planadas", deparmentService.getDepartmentById(73)));
			cities.add(new City(674,"Planeta Rica", deparmentService.getDepartmentById(23)));
			cities.add(new City(675,"Plato", deparmentService.getDepartmentById(47)));
			cities.add(new City(676,"Policarpa", deparmentService.getDepartmentById(52)));
			cities.add(new City(677,"Polonuevo", deparmentService.getDepartmentById(8)));
			cities.add(new City(678,"Ponedera", deparmentService.getDepartmentById(8)));
			cities.add(new City(679,"Popayán", deparmentService.getDepartmentById(19)));
			cities.add(new City(680,"Pore", deparmentService.getDepartmentById(85)));
			cities.add(new City(681,"Potosí", deparmentService.getDepartmentById(52)));
			cities.add(new City(682,"Pradera", deparmentService.getDepartmentById(76)));
			cities.add(new City(683,"Prado", deparmentService.getDepartmentById(73)));
			cities.add(new City(684,"Providencia", deparmentService.getDepartmentById(52)));
			cities.add(new City(685,"Providencia", deparmentService.getDepartmentById(88)));
			cities.add(new City(686,"Pueblo Bello", deparmentService.getDepartmentById(20)));
			cities.add(new City(687,"Pueblo Nuevo", deparmentService.getDepartmentById(23)));
			cities.add(new City(688,"Pueblo Rico", deparmentService.getDepartmentById(66)));
			cities.add(new City(689,"Pueblorrico", deparmentService.getDepartmentById(5)));
			cities.add(new City(690,"Puebloviejo", deparmentService.getDepartmentById(47)));
			cities.add(new City(691,"Puente Nacional", deparmentService.getDepartmentById(68)));
			cities.add(new City(692,"Puerres", deparmentService.getDepartmentById(52)));
			cities.add(new City(693,"Puerto Asís", deparmentService.getDepartmentById(86)));
			cities.add(new City(694,"Puerto Berrío", deparmentService.getDepartmentById(5)));
			cities.add(new City(695,"Puerto Boyacá", deparmentService.getDepartmentById(15)));
			cities.add(new City(696,"Puerto Caicedo", deparmentService.getDepartmentById(86)));
			cities.add(new City(697,"Puerto Carreño", deparmentService.getDepartmentById(99)));
			cities.add(new City(698,"Puerto Colombia", deparmentService.getDepartmentById(8)));
			cities.add(new City(699,"Puerto Concordia", deparmentService.getDepartmentById(50)));
			cities.add(new City(700,"Puerto Escondido", deparmentService.getDepartmentById(23)));
			cities.add(new City(701,"Puerto Gaitán", deparmentService.getDepartmentById(50)));
			cities.add(new City(702,"Puerto Guzmán", deparmentService.getDepartmentById(86)));
			cities.add(new City(703,"Puerto Leguízamo", deparmentService.getDepartmentById(86)));
			cities.add(new City(704,"Puerto Libertador", deparmentService.getDepartmentById(23)));
			cities.add(new City(705,"Puerto Lleras", deparmentService.getDepartmentById(50)));
			cities.add(new City(706,"Puerto López", deparmentService.getDepartmentById(50)));
			cities.add(new City(707,"Puerto Nare", deparmentService.getDepartmentById(5)));
			cities.add(new City(708,"Puerto Nariño", deparmentService.getDepartmentById(91)));
			cities.add(new City(709,"Puerto Parra", deparmentService.getDepartmentById(68)));
			cities.add(new City(710,"Puerto Rico", deparmentService.getDepartmentById(18)));
			cities.add(new City(711,"Puerto Rico", deparmentService.getDepartmentById(50)));
			cities.add(new City(712,"Puerto Rondón", deparmentService.getDepartmentById(81)));
			cities.add(new City(713,"Puerto Salgar", deparmentService.getDepartmentById(25)));
			cities.add(new City(714,"Puerto Santander", deparmentService.getDepartmentById(54)));
			cities.add(new City(715,"Puerto Tejada", deparmentService.getDepartmentById(19)));
			cities.add(new City(716,"Puerto Triunfo", deparmentService.getDepartmentById(5)));
			cities.add(new City(717,"Puerto Wilches", deparmentService.getDepartmentById(68)));
			cities.add(new City(718,"Pulí", deparmentService.getDepartmentById(25)));
			cities.add(new City(719,"Pupiales", deparmentService.getDepartmentById(52)));
			cities.add(new City(720,"Puracé (Coconuco)", deparmentService.getDepartmentById(19)));
			cities.add(new City(721,"Purificación", deparmentService.getDepartmentById(73)));
			cities.add(new City(722,"Purísima", deparmentService.getDepartmentById(23)));
			cities.add(new City(723,"Pácora", deparmentService.getDepartmentById(17)));
			cities.add(new City(724,"Páez", deparmentService.getDepartmentById(15)));
			cities.add(new City(725,"Páez (Belalcazar)", deparmentService.getDepartmentById(19)));
			cities.add(new City(726,"Páramo", deparmentService.getDepartmentById(68)));
			cities.add(new City(727,"Quebradanegra", deparmentService.getDepartmentById(25)));
			cities.add(new City(728,"Quetame", deparmentService.getDepartmentById(25)));
			cities.add(new City(729,"Quibdó", deparmentService.getDepartmentById(27)));
			cities.add(new City(730,"Quimbaya", deparmentService.getDepartmentById(63)));
			cities.add(new City(731,"Quinchía", deparmentService.getDepartmentById(66)));
			cities.add(new City(732,"Quipama", deparmentService.getDepartmentById(15)));
			cities.add(new City(733,"Quipile", deparmentService.getDepartmentById(25)));
			cities.add(new City(734,"Ragonvalia", deparmentService.getDepartmentById(54)));
			cities.add(new City(735,"Ramiriquí", deparmentService.getDepartmentById(15)));
			cities.add(new City(736,"Recetor", deparmentService.getDepartmentById(85)));
			cities.add(new City(737,"Regidor", deparmentService.getDepartmentById(13)));
			cities.add(new City(738,"Remedios", deparmentService.getDepartmentById(5)));
			cities.add(new City(739,"Remolino", deparmentService.getDepartmentById(47)));
			cities.add(new City(740,"Repelón", deparmentService.getDepartmentById(8)));
			cities.add(new City(741,"Restrepo", deparmentService.getDepartmentById(50)));
			cities.add(new City(742,"Restrepo", deparmentService.getDepartmentById(76)));
			cities.add(new City(743,"Retiro", deparmentService.getDepartmentById(5)));
			cities.add(new City(744,"Ricaurte", deparmentService.getDepartmentById(25)));
			cities.add(new City(745,"Ricaurte", deparmentService.getDepartmentById(52)));
			cities.add(new City(746,"Rio Negro", deparmentService.getDepartmentById(68)));
			cities.add(new City(747,"Rioblanco", deparmentService.getDepartmentById(73)));
			cities.add(new City(748,"Riofrío", deparmentService.getDepartmentById(76)));
			cities.add(new City(749,"Riohacha", deparmentService.getDepartmentById(44)));
			cities.add(new City(750,"Risaralda", deparmentService.getDepartmentById(17)));
			cities.add(new City(751,"Rivera", deparmentService.getDepartmentById(41)));
			cities.add(new City(752,"Roberto Payán (San José)", deparmentService.getDepartmentById(52)));
			cities.add(new City(753,"Roldanillo", deparmentService.getDepartmentById(76)));
			cities.add(new City(754,"Roncesvalles", deparmentService.getDepartmentById(73)));
			cities.add(new City(755,"Rondón", deparmentService.getDepartmentById(15)));
			cities.add(new City(756,"Rosas", deparmentService.getDepartmentById(19)));
			cities.add(new City(757,"Rovira", deparmentService.getDepartmentById(73)));
			cities.add(new City(758,"Ráquira", deparmentService.getDepartmentById(15)));
			cities.add(new City(759,"Río Iró", deparmentService.getDepartmentById(27)));
			cities.add(new City(760,"Río Quito", deparmentService.getDepartmentById(27)));
			cities.add(new City(761,"Río Sucio", deparmentService.getDepartmentById(17)));
			cities.add(new City(762,"Río Viejo", deparmentService.getDepartmentById(13)));
			cities.add(new City(763,"Río de oro", deparmentService.getDepartmentById(20)));
			cities.add(new City(764,"Ríonegro", deparmentService.getDepartmentById(5)));
			cities.add(new City(765,"Ríosucio", deparmentService.getDepartmentById(27)));
			cities.add(new City(766,"Sabana de Torres", deparmentService.getDepartmentById(68)));
			cities.add(new City(767,"Sabanagrande", deparmentService.getDepartmentById(8)));
			cities.add(new City(768,"Sabanalarga", deparmentService.getDepartmentById(5)));
			cities.add(new City(769,"Sabanalarga", deparmentService.getDepartmentById(8)));
			cities.add(new City(770,"Sabanalarga", deparmentService.getDepartmentById(85)));
			cities.add(new City(771,"Sabanas de San Angel (SAN ANGEL)", deparmentService.getDepartmentById(47)));
			cities.add(new City(772,"Sabaneta", deparmentService.getDepartmentById(5)));
			cities.add(new City(773,"Saboyá", deparmentService.getDepartmentById(15)));
			cities.add(new City(774,"Sahagún", deparmentService.getDepartmentById(23)));
			cities.add(new City(775,"Saladoblanco", deparmentService.getDepartmentById(41)));
			cities.add(new City(776,"Salamina", deparmentService.getDepartmentById(17)));
			cities.add(new City(777,"Salamina", deparmentService.getDepartmentById(47)));
			cities.add(new City(778,"Salazar", deparmentService.getDepartmentById(54)));
			cities.add(new City(779,"Saldaña", deparmentService.getDepartmentById(73)));
			cities.add(new City(780,"Salento", deparmentService.getDepartmentById(63)));
			cities.add(new City(781,"Salgar", deparmentService.getDepartmentById(5)));
			cities.add(new City(782,"Samacá", deparmentService.getDepartmentById(15)));
			cities.add(new City(783,"Samaniego", deparmentService.getDepartmentById(52)));
			cities.add(new City(784,"Samaná", deparmentService.getDepartmentById(17)));
			cities.add(new City(785,"Sampués", deparmentService.getDepartmentById(70)));
			cities.add(new City(786,"San Agustín", deparmentService.getDepartmentById(41)));
			cities.add(new City(787,"San Alberto", deparmentService.getDepartmentById(20)));
			cities.add(new City(788,"San Andrés", deparmentService.getDepartmentById(68)));
			cities.add(new City(789,"San Andrés Sotavento", deparmentService.getDepartmentById(23)));
			cities.add(new City(790,"San Andrés de Cuerquía", deparmentService.getDepartmentById(5)));
			cities.add(new City(791,"San Antero", deparmentService.getDepartmentById(23)));
			cities.add(new City(792,"San Antonio", deparmentService.getDepartmentById(73)));
			cities.add(new City(793,"San Antonio de Tequendama", deparmentService.getDepartmentById(25)));
			cities.add(new City(794,"San Benito", deparmentService.getDepartmentById(68)));
			cities.add(new City(795,"San Benito Abad", deparmentService.getDepartmentById(70)));
			cities.add(new City(796,"San Bernardo", deparmentService.getDepartmentById(25)));
			cities.add(new City(797,"San Bernardo", deparmentService.getDepartmentById(52)));
			cities.add(new City(798,"San Bernardo del Viento", deparmentService.getDepartmentById(23)));
			cities.add(new City(799,"San Calixto", deparmentService.getDepartmentById(54)));
			cities.add(new City(800,"San Carlos", deparmentService.getDepartmentById(5)));
			cities.add(new City(801,"San Carlos", deparmentService.getDepartmentById(23)));
			cities.add(new City(802,"San Carlos de Guaroa", deparmentService.getDepartmentById(50)));
			cities.add(new City(803,"San Cayetano", deparmentService.getDepartmentById(25)));
			cities.add(new City(804,"San Cayetano", deparmentService.getDepartmentById(54)));
			cities.add(new City(805,"San Cristobal", deparmentService.getDepartmentById(13)));
			cities.add(new City(806,"San Diego", deparmentService.getDepartmentById(20)));
			cities.add(new City(807,"San Eduardo", deparmentService.getDepartmentById(15)));
			cities.add(new City(808,"San Estanislao", deparmentService.getDepartmentById(13)));
			cities.add(new City(809,"San Fernando", deparmentService.getDepartmentById(13)));
			cities.add(new City(810,"San Francisco", deparmentService.getDepartmentById(5)));
			cities.add(new City(811,"San Francisco", deparmentService.getDepartmentById(25)));
			cities.add(new City(812,"San Francisco", deparmentService.getDepartmentById(86)));
			cities.add(new City(813,"San Gíl", deparmentService.getDepartmentById(68)));
			cities.add(new City(814,"San Jacinto", deparmentService.getDepartmentById(13)));
			cities.add(new City(815,"San Jacinto del Cauca", deparmentService.getDepartmentById(13)));
			cities.add(new City(816,"San Jerónimo", deparmentService.getDepartmentById(5)));
			cities.add(new City(817,"San Joaquín", deparmentService.getDepartmentById(68)));
			cities.add(new City(818,"San José", deparmentService.getDepartmentById(17)));
			cities.add(new City(819,"San José de Miranda", deparmentService.getDepartmentById(68)));
			cities.add(new City(820,"San José de Montaña", deparmentService.getDepartmentById(5)));
			cities.add(new City(821,"San José de Pare", deparmentService.getDepartmentById(15)));
			cities.add(new City(822,"San José de Uré", deparmentService.getDepartmentById(23)));
			cities.add(new City(823,"San José del Fragua", deparmentService.getDepartmentById(18)));
			cities.add(new City(824,"San José del Guaviare", deparmentService.getDepartmentById(95)));
			cities.add(new City(825,"San José del Palmar", deparmentService.getDepartmentById(27)));
			cities.add(new City(826,"San Juan de Arama", deparmentService.getDepartmentById(50)));
			cities.add(new City(827,"San Juan de Betulia", deparmentService.getDepartmentById(70)));
			cities.add(new City(828,"San Juan de Nepomuceno", deparmentService.getDepartmentById(13)));
			cities.add(new City(829,"San Juan de Pasto", deparmentService.getDepartmentById(52)));
			cities.add(new City(830,"San Juan de Río Seco", deparmentService.getDepartmentById(25)));
			cities.add(new City(831,"San Juan de Urabá", deparmentService.getDepartmentById(5)));
			cities.add(new City(832,"San Juan del Cesar", deparmentService.getDepartmentById(44)));
			cities.add(new City(833,"San Juanito", deparmentService.getDepartmentById(50)));
			cities.add(new City(834,"San Lorenzo", deparmentService.getDepartmentById(52)));
			cities.add(new City(835,"San Luis", deparmentService.getDepartmentById(73)));
			cities.add(new City(836,"San Luís", deparmentService.getDepartmentById(5)));
			cities.add(new City(837,"San Luís de Gaceno", deparmentService.getDepartmentById(15)));
			cities.add(new City(838,"San Luís de Palenque", deparmentService.getDepartmentById(85)));
			cities.add(new City(839,"San Marcos", deparmentService.getDepartmentById(70)));
			cities.add(new City(840,"San Martín", deparmentService.getDepartmentById(20)));
			cities.add(new City(841,"San Martín", deparmentService.getDepartmentById(50)));
			cities.add(new City(842,"San Martín de Loba", deparmentService.getDepartmentById(13)));
			cities.add(new City(843,"San Mateo", deparmentService.getDepartmentById(15)));
			cities.add(new City(844,"San Miguel", deparmentService.getDepartmentById(68)));
			cities.add(new City(845,"San Miguel", deparmentService.getDepartmentById(86)));
			cities.add(new City(846,"San Miguel de Sema", deparmentService.getDepartmentById(15)));
			cities.add(new City(847,"San Onofre", deparmentService.getDepartmentById(70)));
			cities.add(new City(848,"San Pablo", deparmentService.getDepartmentById(13)));
			cities.add(new City(849,"San Pablo", deparmentService.getDepartmentById(52)));
			cities.add(new City(850,"San Pablo de Borbur", deparmentService.getDepartmentById(15)));
			cities.add(new City(851,"San Pedro", deparmentService.getDepartmentById(5)));
			cities.add(new City(852,"San Pedro", deparmentService.getDepartmentById(70)));
			cities.add(new City(853,"San Pedro", deparmentService.getDepartmentById(76)));
			cities.add(new City(854,"San Pedro de Cartago", deparmentService.getDepartmentById(52)));
			cities.add(new City(855,"San Pedro de Urabá", deparmentService.getDepartmentById(5)));
			cities.add(new City(856,"San Pelayo", deparmentService.getDepartmentById(23)));
			cities.add(new City(857,"San Rafael", deparmentService.getDepartmentById(5)));
			cities.add(new City(858,"San Roque", deparmentService.getDepartmentById(5)));
			cities.add(new City(859,"San Sebastián", deparmentService.getDepartmentById(19)));
			cities.add(new City(860,"San Sebastián de Buenavista", deparmentService.getDepartmentById(47)));
			cities.add(new City(861,"San Vicente", deparmentService.getDepartmentById(5)));
			cities.add(new City(862,"San Vicente del Caguán", deparmentService.getDepartmentById(18)));
			cities.add(new City(863,"San Vicente del Chucurí", deparmentService.getDepartmentById(68)));
			cities.add(new City(864,"San Zenón", deparmentService.getDepartmentById(47)));
			cities.add(new City(865,"Sandoná", deparmentService.getDepartmentById(52)));
			cities.add(new City(866,"Santa Ana", deparmentService.getDepartmentById(47)));
			cities.add(new City(867,"Santa Bárbara", deparmentService.getDepartmentById(5)));
			cities.add(new City(868,"Santa Bárbara", deparmentService.getDepartmentById(68)));
			cities.add(new City(869,"Santa Bárbara (Iscuandé)", deparmentService.getDepartmentById(52)));
			cities.add(new City(870,"Santa Bárbara de Pinto", deparmentService.getDepartmentById(47)));
			cities.add(new City(871,"Santa Catalina", deparmentService.getDepartmentById(13)));
			cities.add(new City(872,"Santa Fé de Antioquia", deparmentService.getDepartmentById(5)));
			cities.add(new City(873,"Santa Genoveva de Docorodó", deparmentService.getDepartmentById(27)));
			cities.add(new City(874,"Santa Helena del Opón", deparmentService.getDepartmentById(68)));
			cities.add(new City(875,"Santa Isabel", deparmentService.getDepartmentById(73)));
			cities.add(new City(876,"Santa Lucía", deparmentService.getDepartmentById(8)));
			cities.add(new City(877,"Santa Marta", deparmentService.getDepartmentById(47)));
			cities.add(new City(878,"Santa María", deparmentService.getDepartmentById(15)));
			cities.add(new City(879,"Santa María", deparmentService.getDepartmentById(41)));
			cities.add(new City(880,"Santa Rosa", deparmentService.getDepartmentById(13)));
			cities.add(new City(881,"Santa Rosa", deparmentService.getDepartmentById(19)));
			cities.add(new City(882,"Santa Rosa de Cabal", deparmentService.getDepartmentById(66)));
			cities.add(new City(883,"Santa Rosa de Osos", deparmentService.getDepartmentById(5)));
			cities.add(new City(884,"Santa Rosa de Viterbo", deparmentService.getDepartmentById(15)));
			cities.add(new City(885,"Santa Rosa del Sur", deparmentService.getDepartmentById(13)));
			cities.add(new City(886,"Santa Rosalía", deparmentService.getDepartmentById(99)));
			cities.add(new City(887,"Santa Sofía", deparmentService.getDepartmentById(15)));
			cities.add(new City(888,"Santana", deparmentService.getDepartmentById(15)));
			cities.add(new City(889,"Santander de Quilichao", deparmentService.getDepartmentById(19)));
			cities.add(new City(890,"Santiago", deparmentService.getDepartmentById(54)));
			cities.add(new City(891,"Santiago", deparmentService.getDepartmentById(86)));
			cities.add(new City(892,"Santo Domingo", deparmentService.getDepartmentById(5)));
			cities.add(new City(893,"Santo Tomás", deparmentService.getDepartmentById(8)));
			cities.add(new City(894,"Santuario", deparmentService.getDepartmentById(5)));
			cities.add(new City(895,"Santuario", deparmentService.getDepartmentById(66)));
			cities.add(new City(896,"Sapuyes", deparmentService.getDepartmentById(52)));
			cities.add(new City(897,"Saravena", deparmentService.getDepartmentById(81)));
			cities.add(new City(898,"Sardinata", deparmentService.getDepartmentById(54)));
			cities.add(new City(899,"Sasaima", deparmentService.getDepartmentById(25)));
			cities.add(new City(900,"Sativanorte", deparmentService.getDepartmentById(15)));
			cities.add(new City(901,"Sativasur", deparmentService.getDepartmentById(15)));
			cities.add(new City(902,"Segovia", deparmentService.getDepartmentById(5)));
			cities.add(new City(903,"Sesquilé", deparmentService.getDepartmentById(25)));
			cities.add(new City(904,"Sevilla", deparmentService.getDepartmentById(76)));
			cities.add(new City(905,"Siachoque", deparmentService.getDepartmentById(15)));
			cities.add(new City(906,"Sibaté", deparmentService.getDepartmentById(25)));
			cities.add(new City(907,"Sibundoy", deparmentService.getDepartmentById(86)));
			cities.add(new City(908,"Silos", deparmentService.getDepartmentById(54)));
			cities.add(new City(909,"Silvania", deparmentService.getDepartmentById(25)));
			cities.add(new City(910,"Silvia", deparmentService.getDepartmentById(19)));
			cities.add(new City(911,"Simacota", deparmentService.getDepartmentById(68)));
			cities.add(new City(912,"Simijaca", deparmentService.getDepartmentById(25)));
			cities.add(new City(913,"Simití", deparmentService.getDepartmentById(13)));
			cities.add(new City(914,"Sincelejo", deparmentService.getDepartmentById(70)));
			cities.add(new City(915,"Sincé", deparmentService.getDepartmentById(70)));
			cities.add(new City(916,"Sipí", deparmentService.getDepartmentById(27)));
			cities.add(new City(917,"Sitionuevo", deparmentService.getDepartmentById(47)));
			cities.add(new City(918,"Soacha", deparmentService.getDepartmentById(25)));
			cities.add(new City(919,"Soatá", deparmentService.getDepartmentById(15)));
			cities.add(new City(920,"Socha", deparmentService.getDepartmentById(15)));
			cities.add(new City(921,"Socorro", deparmentService.getDepartmentById(68)));
			cities.add(new City(922,"Socotá", deparmentService.getDepartmentById(15)));
			cities.add(new City(923,"Sogamoso", deparmentService.getDepartmentById(15)));
			cities.add(new City(924,"Solano", deparmentService.getDepartmentById(18)));
			cities.add(new City(925,"Soledad", deparmentService.getDepartmentById(8)));
			cities.add(new City(926,"Solita", deparmentService.getDepartmentById(18)));
			cities.add(new City(927,"Somondoco", deparmentService.getDepartmentById(15)));
			cities.add(new City(928,"Sonsón", deparmentService.getDepartmentById(5)));
			cities.add(new City(929,"Sopetrán", deparmentService.getDepartmentById(5)));
			cities.add(new City(930,"Soplaviento", deparmentService.getDepartmentById(13)));
			cities.add(new City(931,"Sopó", deparmentService.getDepartmentById(25)));
			cities.add(new City(932,"Sora", deparmentService.getDepartmentById(15)));
			cities.add(new City(933,"Soracá", deparmentService.getDepartmentById(15)));
			cities.add(new City(934,"Sotaquirá", deparmentService.getDepartmentById(15)));
			cities.add(new City(935,"Sotara (Paispamba)", deparmentService.getDepartmentById(19)));
			cities.add(new City(936,"Sotomayor (Los Andes)", deparmentService.getDepartmentById(52)));
			cities.add(new City(937,"Suaita", deparmentService.getDepartmentById(68)));
			cities.add(new City(938,"Suan", deparmentService.getDepartmentById(8)));
			cities.add(new City(939,"Suaza", deparmentService.getDepartmentById(41)));
			cities.add(new City(940,"Subachoque", deparmentService.getDepartmentById(25)));
			cities.add(new City(941,"Sucre", deparmentService.getDepartmentById(19)));
			cities.add(new City(942,"Sucre", deparmentService.getDepartmentById(68)));
			cities.add(new City(943,"Sucre", deparmentService.getDepartmentById(70)));
			cities.add(new City(944,"Suesca", deparmentService.getDepartmentById(25)));
			cities.add(new City(945,"Supatá", deparmentService.getDepartmentById(25)));
			cities.add(new City(946,"Supía", deparmentService.getDepartmentById(17)));
			cities.add(new City(947,"Suratá", deparmentService.getDepartmentById(68)));
			cities.add(new City(948,"Susa", deparmentService.getDepartmentById(25)));
			cities.add(new City(949,"Susacón", deparmentService.getDepartmentById(15)));
			cities.add(new City(950,"Sutamarchán", deparmentService.getDepartmentById(15)));
			cities.add(new City(951,"Sutatausa", deparmentService.getDepartmentById(25)));
			cities.add(new City(952,"Sutatenza", deparmentService.getDepartmentById(15)));
			cities.add(new City(953,"Suárez", deparmentService.getDepartmentById(19)));
			cities.add(new City(954,"Suárez", deparmentService.getDepartmentById(73)));
			cities.add(new City(955,"Sácama", deparmentService.getDepartmentById(85)));
			cities.add(new City(956,"Sáchica", deparmentService.getDepartmentById(15)));
			cities.add(new City(957,"Tabio", deparmentService.getDepartmentById(25)));
			cities.add(new City(958,"Tadó", deparmentService.getDepartmentById(27)));
			cities.add(new City(959,"Talaigua Nuevo", deparmentService.getDepartmentById(13)));
			cities.add(new City(960,"Tamalameque", deparmentService.getDepartmentById(20)));
			cities.add(new City(961,"Tame", deparmentService.getDepartmentById(81)));
			cities.add(new City(962,"Taminango", deparmentService.getDepartmentById(52)));
			cities.add(new City(963,"Tangua", deparmentService.getDepartmentById(52)));
			cities.add(new City(964,"Taraira", deparmentService.getDepartmentById(97)));
			cities.add(new City(965,"Tarazá", deparmentService.getDepartmentById(5)));
			cities.add(new City(966,"Tarqui", deparmentService.getDepartmentById(41)));
			cities.add(new City(967,"Tarso", deparmentService.getDepartmentById(5)));
			cities.add(new City(968,"Tasco", deparmentService.getDepartmentById(15)));
			cities.add(new City(969,"Tauramena", deparmentService.getDepartmentById(85)));
			cities.add(new City(970,"Tausa", deparmentService.getDepartmentById(25)));
			cities.add(new City(971,"Tello", deparmentService.getDepartmentById(41)));
			cities.add(new City(972,"Tena", deparmentService.getDepartmentById(25)));
			cities.add(new City(973,"Tenerife", deparmentService.getDepartmentById(47)));
			cities.add(new City(974,"Tenjo", deparmentService.getDepartmentById(25)));
			cities.add(new City(975,"Tenza", deparmentService.getDepartmentById(15)));
			cities.add(new City(976,"Teorama", deparmentService.getDepartmentById(54)));
			cities.add(new City(977,"Teruel", deparmentService.getDepartmentById(41)));
			cities.add(new City(978,"Tesalia", deparmentService.getDepartmentById(41)));
			cities.add(new City(979,"Tibacuy", deparmentService.getDepartmentById(25)));
			cities.add(new City(980,"Tibaná", deparmentService.getDepartmentById(15)));
			cities.add(new City(981,"Tibasosa", deparmentService.getDepartmentById(15)));
			cities.add(new City(982,"Tibirita", deparmentService.getDepartmentById(25)));
			cities.add(new City(983,"Tibú", deparmentService.getDepartmentById(54)));
			cities.add(new City(984,"Tierralta", deparmentService.getDepartmentById(23)));
			cities.add(new City(985,"Timaná", deparmentService.getDepartmentById(41)));
			cities.add(new City(986,"Timbiquí", deparmentService.getDepartmentById(19)));
			cities.add(new City(987,"Timbío", deparmentService.getDepartmentById(19)));
			cities.add(new City(988,"Tinjacá", deparmentService.getDepartmentById(15)));
			cities.add(new City(989,"Tipacoque", deparmentService.getDepartmentById(15)));
			cities.add(new City(990,"Tiquisio (Puerto Rico)", deparmentService.getDepartmentById(13)));
			cities.add(new City(991,"Titiribí", deparmentService.getDepartmentById(5)));
			cities.add(new City(992,"Toca", deparmentService.getDepartmentById(15)));
			cities.add(new City(993,"Tocaima", deparmentService.getDepartmentById(25)));
			cities.add(new City(994,"Tocancipá", deparmentService.getDepartmentById(25)));
			cities.add(new City(995,"Toguí", deparmentService.getDepartmentById(15)));
			cities.add(new City(996,"Toledo", deparmentService.getDepartmentById(5)));
			cities.add(new City(997,"Toledo", deparmentService.getDepartmentById(54)));
			cities.add(new City(998,"Tolú", deparmentService.getDepartmentById(70)));
			cities.add(new City(999,"Tolú Viejo", deparmentService.getDepartmentById(70)));
			cities.add(new City(1000,"Tona", deparmentService.getDepartmentById(68)));
			cities.add(new City(1001,"Topagá", deparmentService.getDepartmentById(15)));
			cities.add(new City(1002,"Topaipí", deparmentService.getDepartmentById(25)));
			cities.add(new City(1003,"Toribío", deparmentService.getDepartmentById(19)));
			cities.add(new City(1004,"Toro", deparmentService.getDepartmentById(76)));
			cities.add(new City(1005,"Tota", deparmentService.getDepartmentById(15)));
			cities.add(new City(1006,"Totoró", deparmentService.getDepartmentById(19)));
			cities.add(new City(1007,"Trinidad", deparmentService.getDepartmentById(85)));
			cities.add(new City(1008,"Trujillo", deparmentService.getDepartmentById(76)));
			cities.add(new City(1009,"Tubará", deparmentService.getDepartmentById(8)));
			cities.add(new City(1010,"Tuchín", deparmentService.getDepartmentById(23)));
			cities.add(new City(1011,"Tulúa", deparmentService.getDepartmentById(76)));
			cities.add(new City(1012,"Tumaco", deparmentService.getDepartmentById(52)));
			cities.add(new City(1013,"Tunja", deparmentService.getDepartmentById(15)));
			cities.add(new City(1014,"Tunungua", deparmentService.getDepartmentById(15)));
			cities.add(new City(1015,"Turbaco", deparmentService.getDepartmentById(13)));
			cities.add(new City(1016,"Turbaná", deparmentService.getDepartmentById(13)));
			cities.add(new City(1017,"Turbo", deparmentService.getDepartmentById(5)));
			cities.add(new City(1018,"Turmequé", deparmentService.getDepartmentById(15)));
			cities.add(new City(1019,"Tuta", deparmentService.getDepartmentById(15)));
			cities.add(new City(1020,"Tutasá", deparmentService.getDepartmentById(15)));
			cities.add(new City(1021,"Támara", deparmentService.getDepartmentById(85)));
			cities.add(new City(1022,"Támesis", deparmentService.getDepartmentById(5)));
			cities.add(new City(1023,"Túquerres", deparmentService.getDepartmentById(52)));
			cities.add(new City(1024,"Ubalá", deparmentService.getDepartmentById(25)));
			cities.add(new City(1025,"Ubaque", deparmentService.getDepartmentById(25)));
			cities.add(new City(1026,"Ubaté", deparmentService.getDepartmentById(25)));
			cities.add(new City(1027,"Ulloa", deparmentService.getDepartmentById(76)));
			cities.add(new City(1028,"Une", deparmentService.getDepartmentById(25)));
			cities.add(new City(1029,"Unguía", deparmentService.getDepartmentById(27)));
			cities.add(new City(1030,"Unión Panamericana (ÁNIMAS)", deparmentService.getDepartmentById(27)));
			cities.add(new City(1031,"Uramita", deparmentService.getDepartmentById(5)));
			cities.add(new City(1032,"Uribe", deparmentService.getDepartmentById(50)));
			cities.add(new City(1033,"Uribia", deparmentService.getDepartmentById(44)));
			cities.add(new City(1034,"Urrao", deparmentService.getDepartmentById(5)));
			cities.add(new City(1035,"Urumita", deparmentService.getDepartmentById(44)));
			cities.add(new City(1036,"Usiacuri", deparmentService.getDepartmentById(8)));
			cities.add(new City(1037,"Valdivia", deparmentService.getDepartmentById(5)));
			cities.add(new City(1038,"Valencia", deparmentService.getDepartmentById(23)));
			cities.add(new City(1039,"Valle de San José", deparmentService.getDepartmentById(68)));
			cities.add(new City(1040,"Valle de San Juan", deparmentService.getDepartmentById(73)));
			cities.add(new City(1041,"Valle del Guamuez", deparmentService.getDepartmentById(86)));
			cities.add(new City(1042,"Valledupar", deparmentService.getDepartmentById(20)));
			cities.add(new City(1043,"Valparaiso", deparmentService.getDepartmentById(5)));
			cities.add(new City(1044,"Valparaiso", deparmentService.getDepartmentById(18)));
			cities.add(new City(1045,"Vegachí", deparmentService.getDepartmentById(5)));
			cities.add(new City(1046,"Venadillo", deparmentService.getDepartmentById(73)));
			cities.add(new City(1047,"Venecia", deparmentService.getDepartmentById(5)));
			cities.add(new City(1048,"Venecia (Ospina Pérez)", deparmentService.getDepartmentById(25)));
			cities.add(new City(1049,"Ventaquemada", deparmentService.getDepartmentById(15)));
			cities.add(new City(1050,"Vergara", deparmentService.getDepartmentById(25)));
			cities.add(new City(1051,"Versalles", deparmentService.getDepartmentById(76)));
			cities.add(new City(1052,"Vetas", deparmentService.getDepartmentById(68)));
			cities.add(new City(1053,"Viani", deparmentService.getDepartmentById(25)));
			cities.add(new City(1054,"Vigía del Fuerte", deparmentService.getDepartmentById(5)));
			cities.add(new City(1055,"Vijes", deparmentService.getDepartmentById(76)));
			cities.add(new City(1056,"Villa Caro", deparmentService.getDepartmentById(54)));
			cities.add(new City(1057,"Villa Rica", deparmentService.getDepartmentById(19)));
			cities.add(new City(1058,"Villa de Leiva", deparmentService.getDepartmentById(15)));
			cities.add(new City(1059,"Villa del Rosario", deparmentService.getDepartmentById(54)));
			cities.add(new City(1060,"Villagarzón", deparmentService.getDepartmentById(86)));
			cities.add(new City(1061,"Villagómez", deparmentService.getDepartmentById(25)));
			cities.add(new City(1062,"Villahermosa", deparmentService.getDepartmentById(73)));
			cities.add(new City(1063,"Villamaría", deparmentService.getDepartmentById(17)));
			cities.add(new City(1064,"Villanueva", deparmentService.getDepartmentById(13)));
			cities.add(new City(1065,"Villanueva", deparmentService.getDepartmentById(44)));
			cities.add(new City(1066,"Villanueva", deparmentService.getDepartmentById(68)));
			cities.add(new City(1067,"Villanueva", deparmentService.getDepartmentById(85)));
			cities.add(new City(1068,"Villapinzón", deparmentService.getDepartmentById(25)));
			cities.add(new City(1069,"Villarrica", deparmentService.getDepartmentById(73)));
			cities.add(new City(1070,"Villavicencio", deparmentService.getDepartmentById(50)));
			cities.add(new City(1071,"Villavieja", deparmentService.getDepartmentById(41)));
			cities.add(new City(1072,"Villeta", deparmentService.getDepartmentById(25)));
			cities.add(new City(1073,"Viotá", deparmentService.getDepartmentById(25)));
			cities.add(new City(1074,"Viracachá", deparmentService.getDepartmentById(15)));
			cities.add(new City(1075,"Vista Hermosa", deparmentService.getDepartmentById(50)));
			cities.add(new City(1076,"Viterbo", deparmentService.getDepartmentById(17)));
			cities.add(new City(1077,"Vélez", deparmentService.getDepartmentById(68)));
			cities.add(new City(1078,"Yacopí", deparmentService.getDepartmentById(25)));
			cities.add(new City(1079,"Yacuanquer", deparmentService.getDepartmentById(52)));
			cities.add(new City(1080,"Yaguará", deparmentService.getDepartmentById(41)));
			cities.add(new City(1081,"Yalí", deparmentService.getDepartmentById(5)));
			cities.add(new City(1082,"Yarumal", deparmentService.getDepartmentById(5)));
			cities.add(new City(1083,"Yolombó", deparmentService.getDepartmentById(5)));
			cities.add(new City(1084,"Yondó (Casabe)", deparmentService.getDepartmentById(5)));
			cities.add(new City(1085,"Yopal", deparmentService.getDepartmentById(85)));
			cities.add(new City(1086,"Yotoco", deparmentService.getDepartmentById(76)));
			cities.add(new City(1087,"Yumbo", deparmentService.getDepartmentById(76)));
			cities.add(new City(1088,"Zambrano", deparmentService.getDepartmentById(13)));
			cities.add(new City(1089,"Zapatoca", deparmentService.getDepartmentById(68)));
			cities.add(new City(1090,"Zapayán (PUNTA DE PIEDRAS)", deparmentService.getDepartmentById(47)));
			cities.add(new City(1091,"Zaragoza", deparmentService.getDepartmentById(5)));
			cities.add(new City(1092,"Zarzal", deparmentService.getDepartmentById(76)));
			cities.add(new City(1093,"Zetaquirá", deparmentService.getDepartmentById(15)));
			cities.add(new City(1094,"Zipacón", deparmentService.getDepartmentById(25)));
			cities.add(new City(1095,"Zipaquirá", deparmentService.getDepartmentById(25)));
			cities.add(new City(1096,"Zona Bananera (PRADO - SEVILLA)", deparmentService.getDepartmentById(47)));
			cities.add(new City(1097,"Ábrego", deparmentService.getDepartmentById(54)));
			cities.add(new City(1098,"Íquira", deparmentService.getDepartmentById(41)));
			cities.add(new City(1099,"Úmbita", deparmentService.getDepartmentById(15)));
			cities.add(new City(1100,"Útica", deparmentService.getDepartmentById(25)));
			
			
			cityService.saveAllCities(cities);
		}
		
	}
	
	private void setUpDepartments() {
		
		if(deparmentService.getDepartments().isEmpty()) {
			List<Department> departments = new ArrayList<>();
			departments.add(new Department(5, "ANTIOQUIA"));
			departments.add(new Department(8, "ATLÁNTICO"));
			departments.add(new Department(11, "BOGOTÁ, D.C."));
			departments.add(new Department(13, "BOLÍVAR"));
			departments.add(new Department(15, "BOYACÁ"));
			departments.add(new Department(17, "CALDAS"));
			departments.add(new Department(18, "CAQUETÁ"));
			departments.add(new Department(19, "CAUCA"));
			departments.add(new Department(20, "CESAR"));
			departments.add(new Department(23, "CÓRDOBA"));
			departments.add(new Department(25, "CUNDINAMARCA"));
			departments.add(new Department(27, "CHOCÓ"));
			departments.add(new Department(41, "HUILA"));
			departments.add(new Department(44, "LA GUAJIRA"));
			departments.add(new Department(47, "MAGDALENA"));
			departments.add(new Department(50, "META"));
			departments.add(new Department(52, "NARIÑO"));
			departments.add(new Department(54, "NORTE DE SANTANDER"));
			departments.add(new Department(63, "QUINDIO"));
			departments.add(new Department(66, "RISARALDA"));
			departments.add(new Department(68, "SANTANDER"));
			departments.add(new Department(70, "SUCRE"));
			departments.add(new Department(73, "TOLIMA"));
			departments.add(new Department(76, "VALLE DEL CAUCA"));
			departments.add(new Department(81, "ARAUCA"));
			departments.add(new Department(85, "CASANARE"));
			departments.add(new Department(86, "PUTUMAYO"));
			departments.add(new Department(88, "ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA"));
			departments.add(new Department(91, "AMAZONAS"));
			departments.add(new Department(94, "GUAINÍA"));
			departments.add(new Department(95, "GUAVIARE"));
			departments.add(new Department(97, "VAUPÉS"));
			departments.add(new Department(99, "VICHADA"));
			
			deparmentService.saveAllDepartments(departments);
		}
		
		
	}

}
